let initialState={
  levels: [
    [
      [1, 'Present Simple - indiki sadə zaman. Əvəzliklər, also, so'],
      [2, 'Qeyri-müəyyən artikl a(an) və onun istifadə halları'],
      [3, 'He/she/it + fel konstruksiyada sonluq nüansları'],
      [4, 'Əvəzliklərin istifadə qaydaları. müəyyən artikl - the'],
      [5, 'Əvəzliklərin istifadə qaydaları'],
      [6, 'I want, I want to konstruksiyalar'],
      [7, 'I like, I would like konstruksiyalar'],
      [8, 'İndiki sadə zamanda inkar forması'],
      [9, 'İndiki sadə zamanda inkar forması'],
      [10, 'I need, I need to konstruksiyalar'],
      [11, 'Indiki sadə zamanda sual forması. Do I/you/we/they'],
      [12, 'Indiki sadə zamanda sual forması. Does he/she/it'],
      [13, 'Indiki sadə zamanda sual forması. Does this/that. Do these/those'],
      [14, 'Indiki sadə zamanda sual forması. Bəzi çətin nüanslar'],
      [15, 'Indiki sadə zamanda xüsusi suallar. What kind of konstruksiyası'],
      [16, 'Indiki sadə zamanda xüsusi suallar'],
      [17, 'Indiki sadə zamanda xüsusi suallar. How much, how many konstruksiyalar'],
      [18, 'Indiki sadə zaman təsdiq, sual və inkar formaları birlikdə'],
      [19, 'Indiki sadə zaman təsdiq, sual və inkar formaları birlikdə'],
      [20, 'I like, I want, I need və digər konstruksiyalar birlikdə'],
      [21, 'Indiki sadə zamand hüsusi suallar yeni sözlər ilə'],
      [22, 'Very much, very hard idadələr. Always/often/usually'],
      [23, 'To be fel və onun formaları'],
      [24, 'To be fel və onun formaları. Müyyən və qeyri-müyyən artikl'],
      [25, 'So/such istifadə qaydası'],
      [26, 'To be fel forması və bəzi məqamlar. Müyyən və qeyri-müyyən artikl'],
      [27, 'To be fel forması köməyi ilə inkar'],
      [28, 'To be fel forması köməyi ilə sual'],
      [29, 'To be fel forması köməyi ilə sual'],
      [30, 'To be fel forması köməyi ilə xüsusi suallar'],
      [31,],
      [32,],
      [33,],
      [34,],
      [35,],
    ],
    [
      [1],
      [2],
      [3],
      [4],
      [5],
      [6],
      [7],
      [8],
      [9],
      [10],
      [11],
      [12],
      [13],
      [14],
      [15],
      [16],
      [17],
      [18],
      [19],
      [20],
      [21],
      [22],
      [23],
      [24],
      [25],
      [26],
      [27],
      [28],
      [29],
      [30],
      [31],
      [32],
      [33],
      [34],
      [35],
      [36],
      [37],
      [38],
      [39],
      [40],
      [41],
      [42],
      [43],
      [44],
      [45],
      [46],
      [47],
      [48],
      [49],
      [50]
    ],
    [
      [1],
      [2],
      [3],
      [4],
      [5],
      [6],
      [7],
      [8],
      [9],
      [10],
      [11],
      [12],
      [13],
      [14],
      [15],
      [16],
      [17],
      [18],
      [19],
      [20],
      [21],
      [22],
      [23],
      [24],
      [25],
      [26],
      [27],
      [28],
      [29],
      [30],
      [31],
      [32],
      [33],
      [34],
      [35],
      [36],
      [37],
      [38],
      [39],
      [40],
      [41],
      [42],
      [43],
      [44],
      [45],
      [46],
      [47],
      [48],
      [49],
      [50],
    ],
    [
      [1],
      [2],
      [3],
      [4],
      [5],
      [6],
      [7],
      [8],
      [9],
      [10],
      [11],
      [12],
      [13],
      [14],
      [15],
      [16],
      [17],
      [18],
      [19],
      [20],
      [21],
      [22],
      [23],
      [24],
      [25],
      [26],
      [27],
      [28],
      [29],
      [30],
      [31],
      [32],
      [33],
      [34],
      [35],
      [36],
      [37],
      [38],
      [39],
      [40],
      [41],
      [42],
      [43],
      [44],
      [45],
      [46],
      [47],
      [48],
      [49],
      [50]
    ],
    [
      [1],
      [2],
      [3],
      [4],
      [5],
      [6],
      [7],
      [8],
      [9],
      [10],
      [11],
      [12],
      [13],
      [14],
      [15],
      [16],
      [17],
      [18],
      [19],
      [20],
      [21],
      [22],
      [23],
      [24],
      [25],
      [26],
      [27],
      [28],
      [29],
      [30],
      [31],
      [32],
      [33],
      [34],
      [35],
      [36],
      [37],
      [38],
      [39],
      [40],
      [41],
      [42],
      [43],
      [44],
      [45],
      [46],
      [47],
      [48],
      [49],
      [50]
    ]
  ]
};


const levelsList = (state = initialState, action) => {
          return state;
  }


export default levelsList
