initialState={
  words: [
[[
{ id: 1, wd: 'I', tr: 'mən' },
{ id: 2, wd: 'think', tr: 'düşünmək' },
{ id: 3, wd: 'we', tr: 'biz' },
{ id: 4, wd: 'understand', tr: 'anlamaq' },
{ id: 5, wd: 'it', tr: 'bu' }],
[{ id: 6, wd: 'speak', tr: 'danışmaq' },
{ id: 7, wd: 'they', tr: 'onlar' },
{ id: 8, wd: 'help', tr: 'kömək etmək' },
{ id: 9, wd: 'me', tr: 'mənə, məni' },
{ id: 10, wd: 'she', tr: 'o (qadın cinsi)' }]],
[[
{ id: 11, wd: 'read', tr: 'oxumaq' },
{ id: 12, wd: 'look', tr: 'baxmaq' },
{ id: 13, wd: 'interesting', tr: 'maraqlı' },
{ id: 14, wd: 'very', tr: 'çox' },
{ id: 15, wd: 'hard', tr: 'sərt' }],
[{ id: 16, wd: 'see', tr: 'görmək' },
{ id: 17, wd: 'this', tr: 'bu (işarə əvəzliyi)' },
{ id: 18, wd: 'mistake', tr: 'səhv' },
{ id: 19, wd: 'also', tr: 'həmçinin, eləcə də' },
{ id: 20, wd: 'house', tr: 'ev' }]],
[[
{ id: 21, wd: 'watch', tr: 'baxmaq' },
{ id: 22, wd: 'go', tr: 'getmək' },
{ id: 23, wd: 'school', tr: 'məktəb' },
{ id: 24, wd: 'every', tr: 'hər, hər bir' },
{ id: 25, wd: 'day', tr: 'gün' }],
[{ id: 26, wd: 'miss', tr: 'darıxmaq' },
{ id: 27, wd: 'sometimes', tr: 'bəzən' },
{ id: 28, wd: 'cinema', tr: 'kinoteatr' },
{ id: 29, wd: 'play', tr: 'oynamaq' },
{ id: 30, wd: 'game', tr: 'oyun' }]],
[[
{ id: 31, wd: 'brother', tr: 'qardaş' },
{ id: 32, wd: 'there', tr: 'orada' },
{ id: 33, wd: 'lesson', tr: 'dərs' },
{ id: 34, wd: 'everything', tr: 'hər şey' },
{ id: 35, wd: 'mother', tr: 'ana' }],
[{ id: 36, wd: 'study', tr: 'təhsil almaq' },
{ id: 37, wd: 'always', tr: 'həmişə' },
{ id: 38, wd: 'parent', tr: 'valideyn' },
{ id: 39, wd: 'know', tr: 'bilmək' },
{ id: 40, wd: 'idea', tr: 'ideya, fikir' }]],
[[
{ id: 41, wd: 'more', tr: 'daha çox' },
{ id: 42, wd: 'really', tr: 'həqiqətən, əslində' },
{ id: 43, wd: 'strange', tr: 'qəribə' },
{ id: 44, wd: 'speak', tr: 'danışmaq' },
{ id: 45, wd: 'sister', tr: 'bacı' }],
[{ id: 46, wd: 'live', tr: 'yaşamaq' },
{ id: 47, wd: 'book', tr: 'kitab' },
{ id: 48, wd: 'cat', tr: 'pişik' },
{ id: 49, wd: 'you', tr: 'sən' },
{ id: 50, wd: 'think', tr: 'düşünmek' }]],
[[
  { id: 51, wd: 'and', tr: 'və' },
{ id: 52, wd: 'do', tr: 'etmək' },
{ id: 53, wd: 'buy', tr: 'almaq' },
{ id: 54, wd: 'see', tr: 'görmək' },
{ id: 55, wd: 'abroad', tr: 'xaricdə' }],
[{ id: 56, wd: 'right now', tr: 'indi, bu dəqiqə' },
{ id: 57, wd: 'parent', tr: 'valideyn' },
{ id: 58, wd: 'friend', tr: 'dost' },
{ id: 59, wd: 'again', tr: 'yenə' },
{ id: 60, wd: 'job', tr: 'iş' }],
],
[[{ id: 61, wd: 'she', tr: 'o (qadın cinsi)' },
{ id: 62, wd: 'method', tr: 'metod, üsul' },
{ id: 63, wd: 'go', tr: 'getmək' },
{ id: 64, wd: 'dress', tr: 'paltar' },
{ id: 65, wd: 'doctor', tr: 'həkim' }],
[{ id: 66, wd: 'they', tr: 'onlar' },
{ id: 67, wd: 'like', tr: 'sevmək, bəyənmək' },
{ id: 68, wd: 'useful', tr: 'faydalı' },
{ id: 69, wd: 'drink', tr: 'içmək' },
{ id: 70, wd: 'milk', tr: 'süd' }]],
[[{ id: 71, wd: 'want', tr: 'istəmək' },
{ id: 72, wd: 'know', tr: 'bilmək' },
{ id: 73, wd: 'like', tr: 'sevmək, bəyənmək' },
{ id: 74, wd: 'agree', tr: 'razılaşmaq' },
{ id: 75, wd: 'with', tr: 'ilə' }],
[{ id: 76, wd: 'discuss', tr: 'müzakirə' },
{ id: 77, wd: 'say', tr: 'demək' },
{ id: 78, wd: 'person', tr: 'şəxs, adam' },
{ id: 79, wd: 'find', tr: 'tapmaq' },
{ id: 80, wd: 'good', tr: 'yaxşı' }]],
[[{ id: 81, wd: 'attract', tr: 'cəlb etmək' },
{ id: 82, wd: 'discuss', tr: 'müzakirə etmək' },
{ id: 83, wd: 'fluently', tr: 'səlist, sərbəst' },
{ id: 84, wd: 'offer', tr: 'təklif' },
{ id: 85, wd: 'interesting', tr: 'maraqlı' }],
[{ id: 86, wd: 'son', tr: 'oğul' },
{ id: 87, wd: 'become', tr: 'olmaq' },
{ id: 88, wd: 'teacher', tr: 'müəllim' },
{ id: 89, wd: 'believe', tr: 'inanmaq' },
{ id: 90, wd: 'make', tr: 'etmək, düzəltmək' }]],
[[{ id: 91, wd: 'need', tr: 'ehtiyac, teləbat' },
{ id: 92, wd: 'without', tr: 'olmadan' },
{ id: 93, wd: 'any', tr: 'hər hansı' },
{ id: 94, wd: 'mistake', tr: 'səhv' },
{ id: 95, wd: 'my ', tr: 'mənim' }],
[{ id: 96, wd: 'call', tr: 'zəng' },
{ id: 97, wd: 'them', tr: 'onlara' },
{ id: 98, wd: 'correct ', tr: 'səhvi düzəltmək' },
{ id: 99, wd: 'correctly', tr: 'düzgün' },
{ id: 100, wd: 'improve', tr: 'təkmilləşdirmək' }]],
[[{ id: 101, wd: 'better', tr: 'daha yaxşı' },
{ id: 102, wd: 'often', tr: 'tez-tez' },
{ id: 103, wd: 'use', tr: 'istifadə' },
{ id: 104, wd: 'internet', tr: 'internet' },
{ id: 105, wd: 'show', tr: 'göstərmək' }],
[{ id: 106, wd: 'result', tr: 'nəticə' },
{ id: 107, wd: 'support', tr: 'dəstək' },
{ id: 108, wd: 'everything', tr: 'hər şey' },
{ id: 109, wd: 'work', tr: 'işləmək, iş' },
{ id: 110, wd: 'with', tr: 'ilə' }]],
[[{ id: 111, wd: 'seem', tr: 'görünmək, gəlmək' },
{ id: 112, wd: 'boring', tr: 'darıxdırıcı' },
{ id: 113, wd: 'abroad', tr: 'xaricdə' },
{ id: 114, wd: 'hate', tr: 'nifrət' },
{ id: 115, wd: 'ignore', tr: 'məhəl qoymamaq' }],
[{ id: 116, wd: 'happen', tr: 'baş vermək' },
{ id: 117, wd: 'pay', tr: 'ödəmək' },
{ id: 118, wd: 'look for', tr: 'axtarmaq' },
{ id: 119, wd: 'thing', tr: 'şey, əşya' },
{ id: 120, wd: 'word', tr: 'söz' }]],
[[{ id: 121, wd: 'important', tr: 'vacib' },
{ id: 122, wd: 'him', tr: 'onu, ona' },
{ id: 123, wd: 'truth', tr: 'həqiqət' },
{ id: 124, wd: 'those', tr: 'onlar' },
{ id: 125, wd: 'student', tr: 'tələbə' }],
[{ id: 126, wd: 'mother', tr: 'ana' },
{ id: 127, wd: 'show', tr: 'göstərmək' },
{ id: 128, wd: 'brilliant', tr: 'parlaq, əla' },
{ id: 129, wd: 'exam', tr: 'imtahan' },
{ id: 130, wd: 'difficult', tr: 'çətin' }]],
[[{ id: 131, wd: 'word', tr: 'söz' },
{ id: 132, wd: 'her', tr: 'onun (qadın cinsi)' },
{ id: 133, wd: 'like', tr: 'sevmək, bəyənmək' },
{ id: 134, wd: 'come', tr: 'gəlmək' },
{ id: 135, wd: 'late', tr: 'gec' }],
[{ id: 136, wd: 'home', tr: 'ev' },
{ id: 137, wd: 'work', tr: 'işləmək, iş' },
{ id: 138, wd: 'solve', tr: 'həll etmək' },
{ id: 139, wd: 'interest', tr: 'maraq' },
{ id: 140, wd: 'happen', tr: 'baş vermək' }]],
[[{ id: 141, wd: 'where', tr: 'harada' },
{ id: 142, wd: 'why', tr: 'nə üçün' },
{ id: 143, wd: 'how', tr: 'necə' },
{ id: 144, wd: 'when', tr: 'nə vaxt' },
{ id: 145, wd: 'free', tr: 'sərbəst, pulsuz' }],
[{ id: 146, wd: 'time', tr: 'vaxt' },
{ id: 147, wd: 'what', tr: 'nə' },
{ id: 148, wd: 'kind', tr: 'növ, xeyirxah' },
{ id: 149, wd: 'much', tr: 'çox' },
{ id: 150, wd: 'get up', tr: 'qalxmaq' }]],
[[{ id: 151, wd: 'why', tr: 'niyə, nə üçün' },
{ id: 152, wd: 'complain', tr: 'şikayət etmək' },
{ id: 153, wd: 'refuse', tr: 'rədd etmək' },
{ id: 154, wd: 'add', tr: 'əlavə etmək' },
{ id: 155, wd: 'prefer', tr: 'üstünlük vermək' }],
[{ id: 156, wd: 'which', tr: 'hansı' },
{ id: 157, wd: 'channel', tr: 'kanal' },
{ id: 158, wd: 'long', tr: 'müddət, vaxt' },
{ id: 159, wd: 'take', tr: 'götürmək' },
{ id: 160, wd: 'get', tr: 'çatmaq' }]],
[[{ id: 161, wd: 'where', tr: 'harada' },
{ id: 162, wd: 'disagree', tr: 'razılaşmamaq' },
{ id: 163, wd: 'control', tr: 'nəzarət' },
{ id: 164, wd: 'leave', tr: 'tərk etmək' },
{ id: 165, wd: 'order', tr: 'sifariş' }],
[{ id: 166, wd: 'teacher', tr: 'müəllim' },
{ id: 167, wd: 'give', tr: 'vermək' },
{ id: 168, wd: 'kind', tr: 'növ, xeyirxah' },
{ id: 169, wd: 'example', tr: 'nümunə' },
{ id: 170, wd: 'business', tr: 'biznes' }]],
[[{ id: 171, wd: 'knowledge', tr: 'bilik' },
{ id: 172, wd: 'better', tr: 'daha yaxşı' },
{ id: 173, wd: 'another', tr: 'başqa' },
{ id: 174, wd: 'what', tr: 'nə, hansı' },
{ id: 175, wd: 'right now', tr: 'indicə' }],
[{ id: 176, wd: 'usually', tr: 'adətən' },
{ id: 177, wd: 'get up', tr: 'ayaqa durmaq' },
{ id: 178, wd: 'feel', tr: 'hiss etmək' },
{ id: 179, wd: 'happy', tr: 'xoşbəxt' },
{ id: 180, wd: 'enough', tr: 'kifayət qədər' }]],
[[{ id: 181, wd: 'how', tr: 'necə' },
{ id: 182, wd: 'person', tr: 'şəxs, adam' },
{ id: 183, wd: 'very', tr: 'çox' },
{ id: 184, wd: 'city', tr: 'şəhər' },
{ id: 185, wd: 'long', tr: 'müddət, vaxt' }],
[{ id: 186, wd: 'daughter', tr: 'qız övladı' },
{ id: 187, wd: 'school', tr: 'məktəb' },
{ id: 188, wd: 'sister', tr: 'bacı' },
{ id: 189, wd: 'live', tr: 'yaşamaq' },
{ id: 190, wd: 'but', tr: 'amma, lakin' }]],
[[{ id: 191, wd: 'try', tr: 'cəhd etmək' },
{ id: 192, wd: 'when', tr: 'nə vaxt' },
{ id: 193, wd: 'free', tr: 'serbəst, pulsuz' },
{ id: 194, wd: 'idea', tr: 'ideya, fikir' },
{ id: 195, wd: 'how', tr: 'necə' }],
[{ id: 196, wd: 'drink', tr: 'içmək' },
{ id: 197, wd: 'coffee', tr: 'qəhvə' },
{ id: 198, wd: 'who', tr: 'kim' },
{ id: 199, wd: 'spend', tr: 'xərcləmək, kəçirmək' },
{ id: 200, wd: 'together', tr: 'birlikdə' }]],
[[{ id: 201, wd: 'book', tr: 'kitab' },
{ id: 202, wd: 'have', tr: 'sahib olmaq' },
{ id: 203, wd: 'home', tr: 'ev' },
{ id: 204, wd: 'music', tr: 'musiqi' },
{ id: 205, wd: 'many', tr: 'çox' }],
[{ id: 206, wd: 'really', tr: 'həqiqətən, əslində' },
{ id: 207, wd: 'correct', tr: 'düzgün' },
{ id: 208, wd: 'also', tr: 'həmçinin, eləcə də' },
{ id: 209, wd: 'brother', tr: 'qardaş' },
{ id: 210, wd: 'exercise', tr: 'tapşırıq, məşq' }]],
[[{ id: 211, wd: 'worry', tr: 'narahat olmaq' },
{ id: 212, wd: 'need', tr: 'ehtiyac' },
{ id: 213, wd: 'tell', tr: 'demək' },
{ id: 214, wd: 'boss', tr: 'müdir' },
{ id: 215, wd: 'always', tr: 'həmişə' }],
[{ id: 216, wd: 'become', tr: 'olmaq' },
{ id: 217, wd: 'read', tr: 'oxumaq' },
{ id: 218, wd: 'improve', tr: 'təkmilləşdirmək' },
{ id: 219, wd: 'grammar', tr: 'qrammatika' },
{ id: 220, wd: 'visit', tr: 'ziyarət etmək' }]],
[[{ id: 221, wd: 'home', tr: 'ev' },
{ id: 222, wd: 'rich', tr: 'zəngin, varlı' },
{ id: 223, wd: 'good', tr: 'yaxşı' },
{ id: 224, wd: 'person', tr: 'şəxs, adam' },
{ id: 225, wd: 'manager', tr: 'menecer' }],
[{ id: 226, wd: 'interesting', tr: 'maraqlı' },
{ id: 227, wd: 'idea', tr: 'ideya, fikir' },
{ id: 228, wd: 'easy', tr: 'asan' },
{ id: 229, wd: 'lazy', tr: 'tənbəl' },
{ id: 230, wd: 'doctor', tr: 'həkim' }]],
[[{ id: 231, wd: 'big', tr: 'böyük' },
{ id: 232, wd: 'simple', tr: 'sadə, asan' },
{ id: 233, wd: 'best', tr: 'ən yaxşı' },
{ id: 234, wd: 'world', tr: 'dünya' },
{ id: 235, wd: 'cheap', tr: 'ucuz' }],
[{ id: 236, wd: 'cold', tr: 'soyuq' },
{ id: 237, wd: 'beautiful', tr: 'gözəl' },
{ id: 238, wd: 'girl', tr: 'qız' },
{ id: 239, wd: 'fine', tr: 'yaxşı, gözəl' },
{ id: 240, wd: 'worse', tr: 'daha pis' }]],
[[{ id: 241, wd: 'such', tr: 'belə, o qədər' },
{ id: 242, wd: 'wise', tr: 'müdrik' },
{ id: 243, wd: 'woman', tr: 'qadın' },
{ id: 244, wd: 'effective', tr: 'effektiv' },
{ id: 245, wd: 'so', tr: 'belə, o qədər' }],
[{ id: 246, wd: 'beautiful', tr: 'gözəl' },
{ id: 247, wd: 'expensive', tr: 'baha' },
{ id: 248, wd: 'clever', tr: 'ağıllı' },
{ id: 249, wd: 'professional', tr: 'peşəkar' },
{ id: 250, wd: 'cheap', tr: 'ucuz' }]],
[[{ id: 251, wd: 'right', tr: 'sağ' },
{ id: 252, wd: 'lesson', tr: 'dərs' },
{ id: 253, wd: 'women', tr: 'qadınlar' },
{ id: 254, wd: 'house', tr: 'ev' },
{ id: 255, wd: 'parent', tr: 'valideyn' }],
[{ id: 256, wd: 'kişilər', tr: 'mən' },
{ id: 257, wd: 'thirty', tr: 'otuz' },
{ id: 258, wd: 'rainy', tr: 'yağmurlu' },
{ id: 259, wd: 'question', tr: 'sual' },
{ id: 260, wd: 'twenty', tr: 'iyirmi' }]],
[[{ id: 261, wd: 'tired', tr: 'yorğun' },
{ id: 262, wd: 'full', tr: 'dolu' },
{ id: 263, wd: 'energy', tr: 'enerji' },
{ id: 264, wd: 'bad', tr: 'pis' },
{ id: 265, wd: 'method', tr: 'metod, üsul' }],
[{ id: 266, wd: 'ineffective', tr: 'qeyri-effektiv' },
{ id: 267, wd: 'woman', tr: 'qadın' },
{ id: 268, wd: 'wise', tr: 'müdrik' },
{ id: 269, wd: 'colleague', tr: 'əməkdaş' },
{ id: 270, wd: 'situation', tr: 'vəziyyət' }]],
[[{ id: 271, wd: 'opinion', tr: 'fikir' },
{ id: 272, wd: 'ready', tr: 'hazır' },
{ id: 273, wd: 'director', tr: 'direktor' },
{ id: 274, wd: 'successful', tr: 'uğurlu' },
{ id: 275, wd: 'project', tr: 'layihə' }],
[{ id: 276, wd: 'obvious', tr: 'açıq-aşkar, aydın' },
{ id: 277, wd: 'global', tr: 'qlobal' },
{ id: 278, wd: 'own', tr: 'sahib' },
{ id: 279, wd: 'flat', tr: 'mənzil' },
{ id: 280, wd: 'boy', tr: 'oğlan' }]],
[[{ id: 281, wd: 'knowledge', tr: 'bilik' },
{ id: 282, wd: 'power', tr: 'güc' },
{ id: 283, wd: 'online', tr: 'onlayn' },
{ id: 284, wd: 'airport', tr: 'hava limanı' },
{ id: 285, wd: 'near', tr: 'yaxın' }],
[{ id: 286, wd: 'level', tr: 'səviyyə' },
{ id: 287, wd: 'article', tr: 'məqalə' },
{ id: 288, wd: 'informative', tr: 'informativ' },
{ id: 289, wd: 'singer', tr: 'müğənni' },
{ id: 290, wd: 'popular', tr: 'populyar' }]],
[[{ id: 291, wd: 'box', tr: 'qutu' },
{ id: 292, wd: 'bag', tr: 'çanta, kisə' },
{ id: 293, wd: 'why', tr: 'nə üçün' },
{ id: 294, wd: 'angry', tr: 'qəzəbli, hirsli' },
{ id: 295, wd: 'when', tr: 'nə vaxt' }],
[{ id: 296, wd: 'who', tr: 'kim' },
{ id: 297, wd: 'work', tr: 'işləmək, iş' },
{ id: 298, wd: 'against', tr: 'əleyhinə' },
{ id: 299, wd: 'far', tr: 'uzaq' },
{ id: 300, wd: 'old', tr: 'köhnə, goca' }]],
[[{ id: 301, wd: 'job', tr: 'iş' },
{ id: 302, wd: 'wrong', tr: 'səhv' },
{ id: 303, wd: 'old', tr: 'köhnə, goca' },
{ id: 304, wd: 'boy', tr: 'oğlan' },
{ id: 305, wd: 'those', tr: 'onlar' }],
[{ id: 306, wd: 'effective', tr: 'effektiv' },
{ id: 307, wd: 'children', tr: 'uşaqlar' },
{ id: 308, wd: 'difficult', tr: 'çətin' },
{ id: 309, wd: 'test', tr: 'sınaq' },
{ id: 310, wd: 'father', tr: 'ata' }]],
[[{ id: 311, wd: 'sunny', tr: 'günəşli' },
{ id: 312, wd: 'from', tr: 'from' },
{ id: 313, wd: 'satisfied', tr: 'qane etmək' },
{ id: 314, wd: 'answer', tr: 'cavab' },
{ id: 315, wd: 'memory', tr: 'yaddaş' }],
[{ id: 316, wd: 'bad', tr: 'pis' },
{ id: 317, wd: 'jeans', tr: 'cins' },
{ id: 318, wd: 'exercise', tr: 'məşq' },
{ id: 319, wd: 'lazy', tr: 'tənbəl' },
{ id: 320, wd: 'dangerous', tr: 'təhlükəli' }]],
[[{ id: 321, wd: 'worse', tr: 'daha pis' },
{ id: 322, wd: 'bathroom', tr: 'hamam' },
{ id: 323, wd: 'kitchen', tr: 'mətbəx' },
{ id: 324, wd: 'boring', tr: 'darıxdırıcı' },
{ id: 325, wd: 'satisfied', tr: 'qane etmək' }],
[{ id: 326, wd: 'box', tr: 'qutu' },
{ id: 327, wd: 'afraid', tr: 'qorxmaq' },
{ id: 328, wd: 'last', tr: 'sonuncu, son' },
{ id: 329, wd: 'enough', tr: 'kifayət qədər' },
{ id: 330, wd: 'news', tr: 'xəbər(-lər)' }]],
[[{ id: 331, wd: 'me', tr: 'mənə, məni' },
{ id: 332, wd: 'right', tr: 'sağ tərəf' },
{ id: 333, wd: 'tired', tr: 'yorğun' },
{ id: 334, wd: 'high', tr: 'yüksək' },
{ id: 335, wd: 'level', tr: 'səviyyə' }],
[{ id: 336, wd: 'manner', tr: 'ədəb' },
{ id: 337, wd: 'against', tr: 'əleyhinə' },
{ id: 338, wd: 'glad', tr: 'şad' },
{ id: 339, wd: 'door', tr: 'qapı' },
{ id: 340, wd: 'open', tr: 'açıq, açmaq' }]],
[[{ id: 341, wd: 'laugh', tr: 'gülmək' },
{ id: 342, wd: 'waste', tr: 'israf etmək' },
{ id: 343, wd: 'summer', tr: 'yay' },
{ id: 344, wd: 'winter', tr: 'qış' },
{ id: 345, wd: 'adapt', tr: 'uyğunlaşma' }],
[{ id: 346, wd: 'condition', tr: 'vəziyyət, şərt' },
{ id: 347, wd: 'soon', tr: 'tezliklə' },
{ id: 348, wd: 'possible', tr: 'mümkün olan' },
{ id: 349, wd: 'prepare', tr: 'hazırlaşmaq' },
{ id: 350, wd: 'exam', tr: 'imtahan' }]],
[[{ id: 351, wd: 'atmosphere', tr: 'ab-hava' },
{ id: 352, wd: 'surprising', tr: 'təəccüblü' },
{ id: 353, wd: 'frighten', tr: 'qorxutmaq' },
{ id: 354, wd: 'nowadays', tr: 'hazırki vaxtda' },
{ id: 355, wd: 'perfectly', tr: 'mükəmməl, çox gözəl' }],
[{ id: 356, wd: 'realize', tr: 'dərk etmək' },
{ id: 357, wd: 'desk', tr: 'yaza masası' },
{ id: 358, wd: 'longest', tr: 'ən uzun' },
{ id: 359, wd: 'river', tr: 'çay' },
{ id: 360, wd: 'write', tr: 'yazmaq'}]],
[[{ id: 361, wd: 'compete', tr: 'rəqabət aparmaq' },
{ id: 362, wd: 'enjoy', tr: 'zövq almaq' },
{ id: 363, wd: 'behave', tr: 'davranmaq' },
{ id: 364, wd: 'strangely', tr: 'qəribə' },
{ id: 365, wd: 'elder', tr: 'daha yaşlı' }],
[{ id: 366, wd: 'younger', tr: 'cavan' },
{ id: 367, wd: 'meaning', tr: 'məna' },
{ id: 368, wd: 'expression', tr: 'İfadə' },
{ id: 369, wd: 'alone', tr: 'tək, tənha' },
{ id: 370, wd: 'experience', tr: 'təcrübə' }]],
[[{ id: 371, wd: 'meaning', tr: 'məna' },
{ id: 372, wd: 'sport', tr: 'idman' },
{ id: 373, wd: 'great', tr: 'böyük' },
{ id: 374, wd: 'sure', tr: 'əmin, arxayın' },
{ id: 375, wd: 'summer', tr: 'yay' }],
[{ id: 376, wd: 'movie', tr: 'film' },
{ id: 377, wd: 'travel', tr: 'səyahət etmək' },
{ id: 378, wd: 'wonderful', tr: 'möhtəşəm, çox gözəl' },
{ id: 379, wd: 'feeling', tr: 'hiss' },
{ id: 380, wd: "o'clock", tr: 'saat' }]],
[[{ id: 381, wd: 'celebrate', tr: 'qeyd etmək' },
{ id: 382, wd: 'birthday', tr: 'ad günü' },
{ id: 383, wd: 'progress', tr: 'progress, tərəqqi' },
{ id: 384, wd: 'enjoy', tr: 'zövq almaq' },
{ id: 385, wd: 'simplicity', tr: 'sadəlik' }],
[{ id: 386, wd: 'hope', tr: 'ümid' },
{ id: 387, wd: 'sad', tr: 'qəmli' },
{ id: 388, wd: 'salary', tr: 'maaş, məvacib' },
{ id: 389, wd: 'low', tr: 'aşagı' },
{ id: 390, wd: 'necessary', tr: 'gərəkli, vacib' }]],
[[{ id: 391, wd: 'fast', tr: 'sürətli' },
{ id: 392, wd: 'business', tr: 'biznes' },
{ id: 393, wd: 'travel', tr: 'səyahət etmək' },
{ id: 394, wd: 'another', tr: 'başqa' },
{ id: 395, wd: 'say', tr: 'demək, söyləmək' }],
[{ id: 396, wd: 'realize', tr: 'dərk etmək' },
{ id: 397, wd: 'talk', tr: 'danışmaq' },
{ id: 398, wd: 'can', tr: 'bacarmaq' },
{ id: 399, wd: 'longer', tr: 'daha uzun' },
{ id: 400, wd: 'may', tr: 'eləyə bilmək' }]],
[[{ id: 401, wd: 'detail', tr: 'detal, hissə' }, //need delete
{ id: 402, wd: 'trousers', tr: 'şalvar' },
{ id: 403, wd: 'tourist', tr: 'turist' },
{ id: 404, wd: 'success', tr: 'müvəffəqiyyət, uğur' },
{ id: 405, wd: 'teach', tr: 'öyrətmək' }],
[{ id: 406, wd: 'year', tr: 'il' },
{ id: 407, wd: 'young', tr: 'gənc, cavan' },
{ id: 408, wd: 'man', tr: 'adam, kişi' },
{ id: 409, wd: 'two', tr: 'iki' },
{ id: 410, wd: 'small', tr: 'balaca' }]],
[[{ id: 411, wd: 'mother', tr: 'ana' },
{ id: 412, wd: 'elementary', tr: 'elementar' },
{ id: 413, wd: 'advanced', tr: 'qabaqcıl' },
{ id: 414, wd: 'trousers', tr: 'şalvar' },
{ id: 415, wd: 'small', tr: 'balaca' }],
[{ id: 416, wd: 'admire', tr: 'heyran olmaq' },
{ id: 417, wd: 'example', tr: 'nümunə' },
{ id: 418, wd: 'informative', tr: 'informativ' },
{ id: 419, wd: 'worse', tr: 'daha pis' },
{ id: 420, wd: 'tall', tr: 'hündür' }]],
[[{ id: 421, wd: 'polite', tr: 'nəzakətli' },
{ id: 422, wd: 'hard-working', tr: 'zəhmətkeş' },
{ id: 423, wd: 'test', tr: 'sınaq' },
{ id: 424, wd: 'here', tr: 'burada' },
{ id: 425, wd: 'learn', tr: 'öyrənmək' }],
[{ id: 426, wd: 'place', tr: 'yer' },
{ id: 427, wd: 'much', tr: 'çox' },
{ id: 428, wd: 'book', tr: 'kitab' },
{ id: 429, wd: 'advertisement', tr: 'reklam' },
{ id: 430, wd: 'opinion', tr: 'rəy, fikir' }]],
[[{ id: 431, wd: 'singer', tr: 'müğənni' },
{ id: 432, wd: 'perfectly', tr: 'əla, mükəmməl' },
{ id: 433, wd: 'lucky', tr: 'şanslı' },
{ id: 434, wd: 'simplicity', tr: 'sadəlik' },
{ id: 435, wd: 'hope', tr: 'ümid etmek' }],
[{ id: 436, wd: 'funny', tr: 'məzəli, gülməli' },
{ id: 437, wd: 'video', tr: 'video' },
{ id: 438, wd: 'year', tr: 'il' },
{ id: 439, wd: 'swim', tr: 'üzmək' },
{ id: 440, wd: 'inspire', tr: 'ilham vermək' }]],
[[{ id: 441, wd: 'joke', tr: 'zarafat' },
{ id: 442, wd: 'choice', tr: 'seçim' },
{ id: 443, wd: 'student', tr: 'tələbə' },
{ id: 444, wd: 'spring', tr: 'bahar' },
{ id: 445, wd: 'bathroom', tr: 'hamam' }],
[{ id: 446, wd: 'unimportant', tr: 'əhəmiyyətsiz' },
{ id: 447, wd: 'powerful', tr: 'güclü' },
{ id: 448, wd: 'presentation', tr: 'təqdimat' },
{ id: 449, wd: 'clear', tr: 'aydın' },
{ id: 450, wd: 'children', tr: 'uşaqlar' }]],
[[{ id: 451, wd: 'autumn', tr: 'payız' },
{ id: 452, wd: 'musician', tr: 'musiqiçi' },
{ id: 453, wd: 'truth', tr: 'həqiqət' },
{ id: 454, wd: 'zoo', tr: 'zoopark' },
{ id: 455, wd: 'library', tr: 'kitabxana' }],
[{ id: 456, wd: 'explanation', tr: 'izah' },
{ id: 457, wd: 'clear', tr: 'aydın' },
{ id: 458, wd: 'unclear', tr: 'aydın olmayan' },
{ id: 459, wd: 'rich', tr: 'zəngin' },
{ id: 460, wd: 'cost', tr: 'qiymət' }]],
[[{ id: 461, wd: 'application', tr: 'tətbiq' },
{ id: 462, wd: 'fantastic', tr: 'fantastik' },
{ id: 463, wd: 'optimistic', tr: 'optimist, nikbin' },
{ id: 464, wd: 'shopping', tr: 'alış-veriş' },
{ id: 465, wd: 'rule', tr: 'qayda' }],
[{ id: 466, wd: 'advanced', tr: 'qabaqcıl' },
{ id: 467, wd: 'food', tr: 'yemək' },
{ id: 468, wd: 'tasty', tr: 'dadlı' },
{ id: 469, wd: 'enough', tr: 'kifayət qədər' },
{ id: 470, wd: 'practice', tr: 'praktika' }]],
[[{ id: 471, wd: 'sunny', tr: 'günəşli' },
{ id: 472, wd: 'magazine', tr: 'jurnal' },
{ id: 473, wd: 'specialist', tr: 'mütəxəssis' },
{ id: 474, wd: 'separately', tr: 'ayrı-ayrılıqda' },
{ id: 475, wd: 'travel', tr: 'səyahət' }],
[{ id: 476, wd: 'pessimistic', tr: 'pessimist' },
{ id: 477, wd: 'frighten', tr: 'qorxutmaq' },
{ id: 478, wd: 'third', tr: 'üçüncü' },
{ id: 479, wd: 'tall', tr: 'hündür' },
{ id: 480, wd: 'answer', tr: 'cavab' }]],
[[{ id: 481, wd: 'recommendation', tr: 'tövsiyə' },
{ id: 482, wd: 'foreign', tr: 'xarici' },
{ id: 483, wd: 'language', tr: 'dil' },
{ id: 484, wd: 'promise', tr: 'vəd etmək' },
{ id: 485, wd: 'trip', tr: 'qısa səyahət' }],
[{ id: 486, wd: 'each', tr: 'hər biri' },
{ id: 487, wd: 'step', tr: 'addım' },
{ id: 488, wd: 'expression', tr: 'İfadə' },
{ id: 489, wd: 'analyze', tr: 'təhlil etmək' },
{ id: 490, wd: 'subject', tr: 'mövzu' }]],
[[{ id: 491, wd: 'spend', tr: 'xərcləmək' },
{ id: 492, wd: 'hospital', tr: 'xəstəxana' },
{ id: 493, wd: 'fluently', tr: 'sərbəst' },
{ id: 494, wd: 'tall', tr: 'hündür' },
{ id: 495, wd: 'nine', tr: 'doqquz' }],
[{ id: 496, wd: 'ten', tr: 'on' },
{ id: 497, wd: 'second', tr: 'ikinci' },
{ id: 498, wd: 'dress', tr: 'paltar' },
{ id: 499, wd: 'cheap', tr: 'ucuz' },
{ id: 500, wd: 'laugh', tr: 'gülmək' }]],
[[{ id: 501, wd: 'create', tr: 'yaratmaq' },
{ id: 502, wd: 'positive', tr: 'müsbət' },
{ id: 503, wd: 'atmosphere', tr: 'ab-hava' },
{ id: 504, wd: 'maximize', tr: 'artırmaq' },
{ id: 505, wd: 'only', tr: 'yalnız' }],
[{ id: 506, wd: 'something', tr: 'bir şey' },
{ id: 507, wd: 'alternative', tr: 'alternativ' },
{ id: 508, wd: 'manipulate', tr: 'manipulyasiya etmək' },
{ id: 509, wd: 'achieve', tr: 'nail olmaq' },
{ id: 510, wd: 'aim', tr: 'məqsəd, hədəf' }]],
[[{ id: 511, wd: 'regulate', tr: 'tənzimləmək' },
{ id: 512, wd: 'somehow', tr: 'hansısa yolla' },
{ id: 513, wd: 'refuse', tr: 'rədd etmək' },
{ id: 514, wd: 'calculate', tr: 'hesablamaq' },
{ id: 515, wd: 'shock', tr: 'sarsıtmaq, şoka salmaq' }],
[{ id: 516, wd: 'borrow', tr: 'borc almaq' },
{ id: 517, wd: 'forget', tr: 'unutmaq' },
{ id: 518, wd: 'health', tr: 'sağlamlıq' },
{ id: 519, wd: 'disappoint', tr: 'məyus etmək' },
{ id: 520, wd: 'forgive', tr: 'bağışlamaq' }]],
[[{ id: 521, wd: 'compete', tr: 'rəqabət aparmaq' },
{ id: 522, wd: 'influence', tr: 'təsir' },
{ id: 523, wd: 'anymore', tr: 'artıq' },
{ id: 524, wd: 'deny', tr: 'inkar' },
{ id: 525, wd: 'contest', tr: 'müsabiqə' }],
[{ id: 526, wd: 'invest', tr: 'investisiya' },
{ id: 527, wd: 'react', tr: 'reaksiya' },
{ id: 528, wd: 'legal', tr: 'qanuni' },
{ id: 529, wd: 'recommend', tr: 'məsləhət' },
{ id: 530, wd: 'guarantee', tr: 'zəmanət' }]],
[[{ id: 531, wd: 'absent', tr: 'iştirak etməyən' },
{ id: 532, wd: 'today', tr: 'bu gün' },
{ id: 533, wd: 'rainy', tr: 'yağışlı' },
{ id: 534, wd: 'grandfather', tr: 'baba' },
{ id: 535, wd: 'initiative', tr: 'təşəbbüs' }],
[{ id: 536, wd: 'guest', tr: 'qonaq' },
{ id: 537, wd: 'notice', tr: 'qeyd etmək' },
{ id: 538, wd: 'absence', tr: 'yoxluq' },
{ id: 539, wd: 'conference', tr: 'konfrans' },
{ id: 540, wd: 'attractive', tr: 'cəlbedici' }]],
[[{ id: 541, wd: 'miss', tr: 'əldən buraxmaq' },
{ id: 542, wd: 'article', tr: 'məqalə' },
{ id: 543, wd: 'for', tr: 'müddətində' },
{ id: 544, wd: 'inform', tr: 'məlumat vermək' },
{ id: 545, wd: 'assistant', tr: 'köməkçi' }],
[{ id: 546, wd: 'celebrate', tr: 'qeyd etmək' },
{ id: 547, wd: 'birthday', tr: 'ad günü' },
{ id: 548, wd: 'commercial', tr: 'ticarət' },
{ id: 549, wd: 'exercise', tr: 'tapşırıq, məşq' },
{ id: 550, wd: 'available', tr: 'mövcud' }]],
[[{ id: 551, wd: 'potential', tr: 'potensial' },
{ id: 552, wd: 'threat', tr: 'təhlükə, hədə-qorxu' },
{ id: 553, wd: 'automatically', tr: 'avtomatik' },
{ id: 554, wd: 'beginning', tr: 'başlanğıc' },
{ id: 555, wd: 'pocket', tr: 'cib' }],
[{ id: 556, wd: 'attitude', tr: 'münasibət' },
{ id: 557, wd: 'health', tr: 'sağlamlıq' },
{ id: 558, wd: 'interest', tr: 'maraqlanmaq' },
{ id: 559, wd: 'sign', tr: 'imzalamaq' },
{ id: 560, wd: 'report', tr: 'hesabat' }]],
[[{ id: 561, wd: 'produce', tr: 'istehsal etmək' },
{ id: 562, wd: 'watch', tr: 'baxmaq' },
{ id: 563, wd: 'fly', tr: 'uçmaq' },
{ id: 564, wd: 'cost', tr: 'qiymət' },
{ id: 565, wd: 'join', tr: 'qoşulmaq' }],
[{ id: 566, wd: 'literature', tr: 'ədəbiyyat' },
{ id: 567, wd: 'come', tr: 'gəlmək' },
{ id: 568, wd: 'back', tr: 'geriyə' },
{ id: 569, wd: 'mean', tr: 'məna' },
{ id: 570, wd: 'material', tr: 'material' }]],
[[{ id: 571, wd: 'offer', tr: 'təklif' },
{ id: 572, wd: 'long', tr: 'müddət, vaxt' },
{ id: 573, wd: 'away', tr: 'uzaqda' },
{ id: 574, wd: 'pleasure', tr: 'həzz, məmnuniyyət' },
{ id: 575, wd: 'fly', tr: 'uçmaq' }],
[{ id: 576, wd: 'event', tr: 'hadisə' },
{ id: 577, wd: 'regret', tr: 'peşman olmaq' },
{ id: 578, wd: 'employee', tr: 'əməkdaş, işçi' },
{ id: 579, wd: 'successful', tr: 'uğurlu' },
{ id: 580, wd: 'continue', tr: 'davam etmək' }]],
[[{ id: 581, wd: 'worker', tr: 'fəhlə, işci' },
{ id: 582, wd: 'resolve', tr: 'həll etmək' },
{ id: 583, wd: 'conflict', tr: 'konflikt' },
{ id: 584, wd: 'championship', tr: 'çempionat' },
{ id: 585, wd: 'reinvent', tr: 'yenidən ixtira' }],
[{ id: 586, wd: 'wheel', tr: 'təkər' },
{ id: 587, wd: 'bus', tr: 'avtobus' },
{ id: 588, wd: 'certainly', tr: 'əlbəttə' },
{ id: 589, wd: 'some', tr: 'bəzi' },
{ id: 590, wd: 'factor', tr: 'amil' }]],
[[{ id: 591, wd: 'owe', tr: 'borclu olmaq' },
{ id: 592, wd: 'competition', tr: 'müsabiqə' },
{ id: 593, wd: 'notice', tr: 'qeyd etmək' },
{ id: 594, wd: 'absence', tr: 'olmama, yoxluq' },
{ id: 595, wd: 'earn', tr: 'qazanmaq' }],
[{ id: 596, wd: 'express', tr: 'ifadə etmək' },
{ id: 597, wd: 'everywhere', tr: 'hər yerdə' },
{ id: 598, wd: 'restaurant', tr: 'restoran' },
{ id: 599, wd: 'impress', tr: 'təsir buraxmaq' },
{ id: 600, wd: 'manipulate', tr: 'manipulyasiya etmək' }]],
[[{ id: 601, wd: 'potential', tr: 'potensial' },
{ id: 602, wd: 'threat', tr: 'təhlükə' },
{ id: 603, wd: 'apologize', tr: 'üzr istə' },
{ id: 604, wd: 'grateful', tr: 'minnətdar' },
{ id: 605, wd: 'family', tr: 'ailə' }],
[{ id: 606, wd: 'necessarily', tr: 'mütləq' },
{ id: 607, wd: 'salary', tr: 'əmək haqqı' },
{ id: 608, wd: 'dictionary', tr: 'lüğət' },
{ id: 609, wd: 'double', tr: 'ikiqat' },
{ id: 610, wd: 'measure', tr: 'tədbir' }]],
[[{ id: 611, wd: 'proud', tr: 'fəxr' },
{ id: 612, wd: 'solution', tr: 'həll olma' },
{ id: 613, wd: 'five', tr: 'beş' },
{ id: 614, wd: 'hundred', tr: 'yüz' },
{ id: 615, wd: 'phrase', tr: 'fraza, ifadə' }],
[{ id: 616, wd: 'fruit', tr: 'meyvə' },
{ id: 617, wd: 'vegetable', tr: 'tərəvəz' },
{ id: 618, wd: 'eat', tr: 'yemək' },
{ id: 619, wd: 'procedure', tr: 'üsul' },
{ id: 620, wd: 'mention', tr: 'xatırlatmaq' }]],
[[{ id: 621, wd: 'easily', tr: 'asanlıqla' },
{ id: 622, wd: 'keep', tr: 'saxlamaq' },
{ id: 623, wd: 'secret', tr: 'sirr' },
{ id: 624, wd: 'despite', tr: 'baxmayaraq' },
{ id: 625, wd: 'crisis', tr: 'böhran' }],
[{ id: 626, wd: 'huge', tr: 'çox böyük' },
{ id: 627, wd: 'educated', tr: 'təhsilli, savadlı' },
{ id: 628, wd: 'native', tr: 'yerli' },
{ id: 629, wd: 'speaker', tr: 'natiq' },
{ id: 630, wd: 'significantly', tr: 'əhəmiyyətli dərəcədə' }]],
[[{ id: 631, wd: 'last', tr: 'axırıncı' },
{ id: 632, wd: 'main', tr: 'əsas' },
{ id: 633, wd: 'everyone', tr: 'hər kəs' },
{ id: 634, wd: 'pronunciation', tr: 'tələffüz' },
{ id: 635, wd: 'authority', tr: 'hakimiyyət' }],
[{ id: 636, wd: 'control', tr: 'nəzarət' },
{ id: 637, wd: 'key', tr: 'açar' },
{ id: 638, wd: 'point', tr: 'nöqtə' },
{ id: 639, wd: 'view', tr: 'baxış' },
{ id: 640, wd: 'insist', tr: 'təkid' }]],
[[{ id: 641, wd: 'forget', tr: 'unutmaq' },
{ id: 642, wd: 'send', tr: 'göndərmək' },
{ id: 643, wd: 'guest', tr: 'qonaq' },
{ id: 644, wd: 'legal', tr: 'qanuni' },
{ id: 645, wd: 'real', tr: 'əsil, həqiqi' }],
[{ id: 646, wd: 'sensation', tr: 'sensasiya' },
{ id: 647, wd: 'chance', tr: 'şans' },
{ id: 648, wd: 'deny', tr: 'inkar etmək' },
{ id: 649, wd: 'intensively', tr: 'intensiv,  gərgin' },
{ id: 650, wd: 'proud', tr: 'fəxr etmək' }]],
[[{ id: 651, wd: 'believe', tr: 'inanmaq' },
{ id: 652, wd: 'repeat', tr: 'təkrar etmək' },
{ id: 653, wd: 'sentence', tr: 'cümlə' },
{ id: 654, wd: 'revise', tr: 'yenidən baxmaq' },
{ id: 655, wd: 'follow', tr: 'İzləmək' }],
[{ id: 656, wd: 'die', tr: 'ölmək' },
{ id: 657, wd: 'create', tr: 'yaratmaq' },
{ id: 658, wd: 'walk', tr: 'piyada getmək' },
{ id: 659, wd: 'move', tr: 'köçmək' },
{ id: 660, wd: 'help', tr: 'kömək etmək' }]],
[[{ id: 661, wd: 'consider', tr: 'hesab etmək' },
{ id: 662, wd: 'one', tr: 'bir' },
{ id: 663, wd: 'window', tr: 'pəncərə' },
{ id: 664, wd: 'wait', tr: 'gözləmək' },
{ id: 665, wd: 'remain', tr: 'qalmaq' }],
[{ id: 666, wd: 'reach', tr: 'çatmaq' },
{ id: 667, wd: 'require', tr: 'tələb etmək' },
{ id: 668, wd: 'effort', tr: 'səy' },
{ id: 669, wd: 'kill', tr: 'öldürmək' },
{ id: 670, wd: 'return', tr: 'qayıtmaq' }]],
[[{ id: 671, wd: 'decide', tr: 'qərara gəlmək' },
{ id: 672, wd: 'strong', tr: 'güclü' },
{ id: 673, wd: 'clothes', tr: 'paltar' },
{ id: 674, wd: 'cake', tr: 'tort' },
{ id: 675, wd: 'invite', tr: 'dəvət etmək' }],
[{ id: 676, wd: 'task', tr: 'tapşırıq' },
{ id: 677, wd: 'record', tr: 'yazmaq' },
{ id: 678, wd: 'advise', tr: 'məsləhət vermək' },
{ id: 679, wd: 'client', tr: 'müştəri' },
{ id: 680, wd: 'thousand', tr: 'min' }]],
[[{ id: 681, wd: 'dish', tr: 'qab' },
{ id: 682, wd: 'delete', tr: 'silmək' },
{ id: 683, wd: 'file', tr: 'fayl' },
{ id: 684, wd: 'divide', tr: 'bölmək' },
{ id: 685, wd: 'part', tr: 'hissə' }],
[{ id: 686, wd: 'concentrate', tr: 'cəmləşmək' },
{ id: 687, wd: 'accuse', tr: 'ittiham etmək' },
{ id: 688, wd: 'crime', tr: 'cinayət' },
{ id: 689, wd: 'last', tr: 'davam etmək' },
{ id: 690, wd: 'cost', tr: 'xərc, məsrəf' }]],
[[{ id: 691, wd: 'ask', tr: 'soruşmaq' },
{ id: 692, wd: 'couple', tr: 'cüt' },
{ id: 693, wd: 'question', tr: 'sual' },
{ id: 694, wd: 'smoke', tr: 'siqaret çəkmək' },
{ id: 695, wd: 'quite', tr: 'olduqca' }],
[{ id: 696, wd: 'rarely', tr: 'nadir hallarda' },
{ id: 697, wd: 'thief', tr: 'oğru' },
{ id: 698, wd: 'speech', tr: 'nitq' },
{ id: 699, wd: 'several', tr: 'bir neçə' },
{ id: 700, wd: 'cry', tr: 'ağlamaq' }]],
[[{ id: 701, wd: 'appearance', tr: 'xarici görünüş' },
{ id: 702, wd: 'defend', tr: 'müdafiə etmək' },
{ id: 703, wd: 'regret', tr: 'peşman olmaq' },
{ id: 704, wd: 'face', tr: 'üzləşmək' },
{ id: 705, wd: 'guess', tr: 'tapmaq' }],
[{ id: 706, wd: 'goods', tr: 'mallar' },
{ id: 707, wd: 'disappeare', tr: 'yox olmaq' },
{ id: 708, wd: 'clearly', tr: 'aydın' },
{ id: 709, wd: 'calm', tr: 'sakit' },
{ id: 710, wd: 'party', tr: 'əyləncə' }]],
[[{ id: 711, wd: 'describe', tr: 'təsvir etmək' },
{ id: 712, wd: 'fail', tr: 'müvəffəq olmamaq' },
{ id: 713, wd: 'partly', tr: 'qismən' },
{ id: 714, wd: 'hate', tr: 'nifrət etmək' },
{ id: 715, wd: 'appearance', tr: 'xarici görünüş' }],
[{ id: 716, wd: 'guess', tr: 'tapmaq' },
{ id: 717, wd: 'face', tr: 'üzləşmək' },
{ id: 718, wd: 'sound', tr: 'səslənmək' },
{ id: 719, wd: 'opportunity', tr: 'fürsət' },
{ id: 720, wd: 'compare', tr: 'müqayisə etmək' }]],
[[{ id: 721, wd: 'destroy', tr: 'məhv etmək' },
{ id: 722, wd: 'earn', tr: 'qazanmaq' },
{ id: 723, wd: 'fact', tr: 'fakt' },
{ id: 724, wd: 'soldier', tr: 'əsgər' },
{ id: 725, wd: 'attack', tr: 'hücum' }],
[{ id: 726, wd: 'deliver', tr: 'çatdırmaq' },
{ id: 727, wd: 'monthly', tr: 'aylıq' },
{ id: 728, wd: 'cook', tr: 'bişirmək' },
{ id: 729, wd: 'something', tr: 'bir şey' },
{ id: 730, wd: 'skill', tr: 'bacarıq' }]],
[[{ id: 731, wd: 'cry', tr: 'ağlamaq' },
{ id: 732, wd: 'suddenly', tr: 'birdən-birə' },
{ id: 733, wd: 'invite', tr: 'dəvət etmək' },
{ id: 734, wd: 'deliver', tr: 'çatdırmaq' },
{ id: 735, wd: 'belong', tr: 'mənsub olmaq' }],
[{ id: 736, wd: 'accusation', tr: 'ittiham' },
{ id: 737, wd: 'jump', tr: 'tullanmaq' },
{ id: 738, wd: 'minute', tr: 'dəqiqə' },
{ id: 739, wd: 'behavior', tr: 'davranış' },
{ id: 740, wd: 'half', tr: 'yarım, yarı' }]],
[[{ id: 741, wd: 'conversation', tr: 'söhbət' },
{ id: 742, wd: 'cross', tr: 'keçmək' },
{ id: 743, wd: 'street', tr: 'küçə' },
{ id: 744, wd: 'dance', tr: 'rəqs etmək' },
{ id: 745, wd: 'admire', tr: 'heyran olmaq' }],
[{ id: 746, wd: 'trust', tr: 'etibar etmək' },
{ id: 747, wd: 'considerably', tr: 'xeyli' },
{ id: 748, wd: 'deserve', tr: 'layiq olmaq' },
{ id: 749, wd: 'completely', tr: 'tamamilə' },
{ id: 750, wd: 'focus', tr: 'diqqəti yönəltmək' }]],
[[{ id: 751, wd: 'thoroughly', tr: 'ətraflı' },
{ id: 752, wd: 'confirm', tr: 'təsdiqləmək' },
{ id: 753, wd: 'discover', tr: 'kəşf etmək' },
{ id: 754, wd: 'snow', tr: 'qar' },
{ id: 755, wd: 'sum', tr: 'məbləğ' }],
[{ id: 756, wd: 'relax', tr: 'dincəlmək' },
{ id: 757, wd: 'saint', tr: 'müqəddəs' },
{ id: 758, wd: 'participate', tr: 'iştirak etmək' },
{ id: 759, wd: 'concentrate', tr: 'cəmləşmək' },
{ id: 760, wd: 'tournament', tr: 'turnir, yarış' }]],
[[{ id: 761, wd: 'group', tr: 'qrup' },
{ id: 762, wd: 'continent', tr: 'qitə' },
{ id: 763, wd: 'pack', tr: 'qablaşdırmaq' },
{ id: 764, wd: 'parcel', tr: 'bağlama' },
{ id: 765, wd: 'serious', tr: 'ciddi' }],
[{ id: 766, wd: 'unexpected', tr: 'gözlənilməyən' },
{ id: 767, wd: 'destroy', tr: 'məhv etmək' },
{ id: 768, wd: 'village', tr: 'kənd' },
{ id: 769, wd: 'suggest', tr: 'təklif etmək' },
{ id: 770, wd: 'discuss', tr: 'müzakirə' }]],
[[{ id: 771, wd: 'grandmother', tr: 'nənə' },
{ id: 772, wd: 'walk', tr: 'piyada getmək' },
{ id: 773, wd: 'trust', tr: 'etibar etmək' },
{ id: 774, wd: 'disappear', tr: 'yox olmaq' },
{ id: 775, wd: 'pray', tr: 'dua etmək' }],
[{ id: 776, wd: 'saint', tr: 'müqəddəs' },
{ id: 777, wd: 'wine', tr: 'şərab, çaxır' },
{ id: 778, wd: 'wish', tr: 'arzu etmək' },
{ id: 779, wd: 'invest', tr: 'investisiya' },
{ id: 780, wd: 'remain', tr: 'qalmaq' }]],
[[{ id: 781, wd: 'concentrate', tr: 'cəmləşmək' },
{ id: 782, wd: 'confirm', tr: 'təsdiqləmək' },
{ id: 783, wd: 'repair', tr: 'təmir etmək' },
{ id: 784, wd: 'chair', tr: 'stul' },
{ id: 785, wd: 'divide', tr: 'bölmək' }],
[{ id: 786, wd: 'appear', tr: 'görünmək' },
{ id: 787, wd: 'enter', tr: 'daxil olmaq' },
{ id: 788, wd: 'smile', tr: 'gülümsəmək' },
{ id: 789, wd: 'kill', tr: 'öldürmək' },
{ id: 790, wd: 'innocent', tr: 'günahsız' }]],
[[{ id: 791, wd: 'provide', tr: 'təmin etmək' },
{ id: 792, wd: 'excellent', tr: 'əla' },
{ id: 793, wd: 'conditions', tr: 'şərait' },
{ id: 794, wd: 'accuse', tr: 'ittiham etmək' },
{ id: 795, wd: 'crime', tr: 'cinayət' }],
[{ id: 796, wd: 'participate', tr: 'iştirak etmək' },
{ id: 797, wd: 'championship', tr: 'çempionat' },
{ id: 798, wd: 'defend', tr: 'müdafiə etmək' },
{ id: 799, wd: 'achieve', tr: 'nail olmaq' },
{ id: 800, wd: 'aim', tr: 'məqsəd, hədəf' }]],
[[{ id: 801, wd: 'thing', tr: 'şey, əşya' },
{ id: 802, wd: 'success', tr: 'müvəffəqiyyət' },
{ id: 803, wd: 'great', tr: 'böyük' },
{ id: 804, wd: 'explain', tr: 'izah etmək' },
{ id: 805, wd: 'well', tr: 'yaxşı' }],
[{ id: 806, wd: 'loudly', tr: 'ucadan' },
{ id: 807, wd: 'again', tr: 'yenə' },
{ id: 808, wd: 'everything', tr: 'hər şey' },
{ id: 809, wd: 'tremendous', tr: 'möhtəşəm' },
{ id: 810, wd: 'return', tr: 'qayıtmaq' }]],
[[{ id: 811, wd: 'disappoint', tr: 'məyus etmək' },
{ id: 812, wd: 'upset', tr: 'kədərləndirmək' },
{ id: 813, wd: 'desk', tr: 'yazı masası' },
{ id: 814, wd: 'wallet', tr: 'pul kisəsi' },
{ id: 815, wd: 'song', tr: 'mahnı' }],
[{ id: 816, wd: 'popular', tr: 'populyar, tanınmış' },
{ id: 817, wd: 'back', tr: 'geri, arxa' },
{ id: 818, wd: 'their', tr: 'onların' },
{ id: 819, wd: 'near', tr: 'yaxın' },
{ id: 820, wd: 'key', tr: 'açar' }]],
[[{ id: 821, wd: 'little', tr: 'balaca, az' },
{ id: 822, wd: 'eight', tr: 'səkkiz' },
{ id: 823, wd: 'excellent', tr: 'əla' },
{ id: 824, wd: 'father', tr: 'ata' },
{ id: 825, wd: 'stay', tr: 'qalmaq' }],
[{ id: 826, wd: 'outstanding', tr: 'görkəmli' },
{ id: 827, wd: 'fast', tr: 'sürətli' },
{ id: 828, wd: 'radio', tr: 'radio' },
{ id: 829, wd: 'word', tr: 'söz' },
{ id: 830, wd: 'first', tr: 'birinci' }]],
[[{ id: 831, wd: 'wallet', tr: 'pul kisəsi' },
{ id: 832, wd: 'unhappy', tr: 'bədbəxt' },
{ id: 833, wd: 'classmate', tr: 'sinif yoldaşı' },
{ id: 834, wd: 'yesterday', tr: 'dünən' },
{ id: 835, wd: 'differently', tr: 'fərqli, müxtəlif' }],
[{ id: 836, wd: 'glass', tr: 'stəkan, şüsə' },
{ id: 837, wd: 'water', tr: 'su' },
{ id: 838, wd: 'heart', tr: 'ürək' },
{ id: 839, wd: 'expression', tr: 'ifadə' },
{ id: 840, wd: 'herself', tr: 'özü, özünə' }]],
[[{ id: 841, wd: 'garden', tr: 'bağ' },
{ id: 842, wd: 'service', tr: 'xidmət' },
{ id: 843, wd: 'discount', tr: 'endirim' },
{ id: 844, wd: 'message', tr: 'mesaj' },
{ id: 845, wd: 'behind', tr: 'arxada, arxasında' }],
[{ id: 846, wd: 'arm', tr: 'əl, qol' },
{ id: 847, wd: 'online', tr: 'onlayn' },
{ id: 848, wd: 'secret', tr: 'sirr' },
{ id: 849, wd: 'chair', tr: 'stul' },
{ id: 850, wd: 'profitable', tr: 'gəlirli, mənfəətli' }]],
[[{ id: 851, wd: 'letter', tr: 'məktub' },
{ id: 852, wd: 'meat', tr: 'ət' },
{ id: 853, wd: 'four', tr: 'dörd' },
{ id: 854, wd: 'piece', tr: 'tikə, hissə' },
{ id: 855, wd: 'fashionable', tr: 'dəbli, modalı' }],
[{ id: 856, wd: 'afraid', tr: 'qorxu' },
{ id: 857, wd: 'incorrectly', tr: 'yanlış, səhv' },
{ id: 858, wd: 'bed', tr: 'yataq' },
{ id: 859, wd: 'window', tr: 'pəncərə' },
{ id: 860, wd: 'notification', tr: 'bildiriş' }]],
[[{ id: 861, wd: 'right', tr: 'hüquq' },
{ id: 862, wd: 'lunch', tr: 'səhər yeməyi' },
{ id: 863, wd: 'customer', tr: 'müştəri' },
{ id: 864, wd: 'camel', tr: 'dəvə' },
{ id: 865, wd: 'uniform', tr: 'rəsmi geyim' }],
[{ id: 866, wd: 'orange', tr: 'portağal' },
{ id: 867, wd: 'juice', tr: 'şirə' },
{ id: 868, wd: 'parcel', tr: 'bağlama' },
{ id: 869, wd: 'apple', tr: 'alma' },
{ id: 870, wd: 'tree', tr: 'ağac' }]],
[[{ id: 871, wd: 'badly', tr: 'pis' },
{ id: 872, wd: 'piece', tr: 'tikə, hissə' },
{ id: 873, wd: 'cake', tr: 'tort, pirojna' },
{ id: 874, wd: 'earlier', tr: 'daha əvvəl' },
{ id: 875, wd: 'cup', tr: 'fincan' }],
[{ id: 876, wd: 'ground', tr: 'yer, torpaq' },
{ id: 877, wd: 'bike', tr: 'velosiped' },
{ id: 878, wd: 'baby', tr: 'körpə' },
{ id: 879, wd: 'independence', tr: 'müstəqillik' },
{ id: 880, wd: 'complaint', tr: 'şikayət' }]],
[[{ id: 881, wd: 'bell', tr: 'zəng' },
{ id: 882, wd: 'clothes', tr: 'paltar' },
{ id: 883, wd: 'boat', tr: 'qayıq' },
{ id: 884, wd: 'ocean', tr: 'okean' },
{ id: 885, wd: 'price', tr: 'qiymət' }],
[{ id: 886, wd: 'twenty', tr: 'İyirmi' },
{ id: 887, wd: 'jewelry', tr: 'daş-qaş' },
{ id: 888, wd: 'usual', tr: 'həmişəki' },
{ id: 889, wd: 'awful', tr: 'dəhşətli' },
{ id: 890, wd: 'jacket', tr: 'jaket' }]],
[[{ id: 891, wd: 'eye', tr: 'göz' },
{ id: 892, wd: 'belt', tr: 'kəmər' },
{ id: 893, wd: 'candle', tr: 'şam' },
{ id: 894, wd: 'dinner', tr: 'şam yeməyi' },
{ id: 895, wd: 'village', tr: 'kənd' }],
[{ id: 896, wd: 'never', tr: 'heç vaxt' },
{ id: 897, wd: 'half', tr: 'yarım, yarı' },
{ id: 898, wd: 'account', tr: 'hesab' },
{ id: 899, wd: 'situation', tr: 'vəziyyət, hal' },
{ id: 900, wd: 'angry', tr: 'qəzəbli, hirsli' }]],
[[{ id: 901, wd: 'quietly', tr: 'sakitcə' },
{ id: 902, wd: 'monthly', tr: 'aylıq' },
{ id: 903, wd: 'bitterly', tr: 'acı-acı, kəskin' },
{ id: 904, wd: 'disappoint', tr: 'məyus etmək' },
{ id: 905, wd: 'instead', tr: 'əvəzinə, yerinə' }],
[{ id: 906, wd: 'never', tr: 'heç vaxt' },
{ id: 907, wd: 'several', tr: 'bir neçə' },
{ id: 908, wd: 'sea', tr: 'dəniz' },
{ id: 909, wd: 'at once', tr: 'bir anda' },
{ id: 910, wd: 'learn', tr: 'öyrənmək' }]],
[[{ id: 911, wd: 'course', tr: 'kurs' },
{ id: 912, wd: 'meat', tr: 'ət' },
{ id: 913, wd: 'notification', tr: 'bildiriş' },
{ id: 914, wd: 'low', tr: 'aşağı' },
{ id: 915, wd: 'unhappy', tr: 'bədbəxt' }],
[{ id: 916, wd: 'usual', tr: 'adətən' },
{ id: 917, wd: 'difficulty', tr: 'çətinlik' },
{ id: 918, wd: 'sandwich', tr: 'səndviç' },
{ id: 919, wd: 'lake', tr: 'göl' },
{ id: 920, wd: 'document', tr: 'sənəd' }]],
[[{ id: 921, wd: 'trouble', tr: 'müsibət' },
{ id: 922, wd: 'bird', tr: 'quş' },
{ id: 923, wd: 'expert', tr: 'mütəxəssis' },
{ id: 924, wd: 'area', tr: 'sahə, ərazi' },
{ id: 925, wd: 'fifteen', tr: 'on beş' }],
[{ id: 926, wd: 'delivery', tr: 'çatdırılma' },
{ id: 927, wd: 'contest', tr: 'müsabiqə' },
{ id: 928, wd: 'seven', tr: 'yeddi' },
{ id: 929, wd: 'light', tr: 'işıq' },
{ id: 930, wd: 'wind', tr: 'külək' }]],
[[{ id: 931, wd: 'o’clock', tr: 'saat' },
{ id: 932, wd: 'afternoon', tr: 'günortadan sonra' },
{ id: 933, wd: 'pair', tr: 'cüt' },
{ id: 934, wd: 'shoes', tr: 'ayaqqabı' },
{ id: 935, wd: 'adapt', tr: 'uyğunlaşmaq' }],
[{ id: 936, wd: 'phrase', tr: 'ifadə, fraza' },
{ id: 937, wd: 'herself', tr: 'özü, özünə' },
{ id: 938, wd: 'armchair', tr: 'kreslo' },
{ id: 939, wd: 'some', tr: 'bəzi, bir neçə' },
{ id: 940, wd: 'little', tr: 'balaca, az' }]],
[[{ id: 941, wd: 'following', tr: 'aşagıdakı, sonraki' },
{ id: 942, wd: 'outstanding', tr: 'möhtəşəm, görkəmli' },
{ id: 943, wd: 'fifteen', tr: 'on beş' },
{ id: 944, wd: 'discount', tr: 'endirim' },
{ id: 945, wd: 'courageously', tr: 'cəsarətlə' }],
[{ id: 946, wd: 'stylish', tr: 'şık' },
{ id: 947, wd: 'complaint', tr: 'şikayət' },
{ id: 948, wd: 'real', tr: 'əsil, həqiqi' },
{ id: 949, wd: 'masterpiece', tr: 'şah əsəri' },
{ id: 950, wd: 'favorite', tr: 'sevimli' }]],
[[{ id: 951, wd: 'jewelry', tr: 'daş-qaş' },
{ id: 952, wd: 'earlier', tr: 'daha əvvəl' },
{ id: 953, wd: 'thief', tr: 'oğru' },
{ id: 954, wd: 'stone', tr: 'daş' },
{ id: 955, wd: 'criminal', tr: 'cinayətkar' }],
[{ id: 956, wd: 'eight', tr: 'səkkiz' },
{ id: 957, wd: 'cycling', tr: 'velosiped sürmək' },
{ id: 958, wd: 'tree', tr: 'ağac' },
{ id: 959, wd: 'swimming pool', tr: 'üzgüçülük hovuzu' },
{ id: 960, wd: 'ship', tr: 'gəmi' }]],
[[{ id: 961, wd: 'fish', tr: 'balıq' },
{ id: 962, wd: 'sweater', tr: 'sviter' },
{ id: 963, wd: 'camel', tr: 'dəvə' },
{ id: 964, wd: 'fashionable', tr: 'dəbli, modalı' },
{ id: 965, wd: 'ball', tr: 'top' }],
[{ id: 966, wd: 'picture', tr: 'şəkil' },
{ id: 967, wd: 'terrible', tr: 'dəhşətli, qorxunc' },
{ id: 968, wd: 'coat', tr: 'palto' },
{ id: 969, wd: 'hook', tr: 'paltarasan' },
{ id: 970, wd: 'horse', tr: 'at' }]],
[[{ id: 971, wd: 'lamp', tr: 'lampa' },
{ id: 972, wd: 'suddenly', tr: 'birdən-birə' },
{ id: 973, wd: 'hole', tr: 'quyu, çala' },
{ id: 974, wd: 'ground', tr: 'yer, torpaq' },
{ id: 975, wd: 'discovery', tr: 'kəşf' }],
[{ id: 976, wd: 'career', tr: 'karyera' },
{ id: 977, wd: 'pond', tr: 'gölməçə' },
{ id: 978, wd: 'leg', tr: 'ayaq' },
{ id: 979, wd: 'feeling', tr: 'hiss' },
{ id: 980, wd: 'bravely', tr: 'cəsarətlə' }]],
[[{ id: 981, wd: 'sun', tr: 'günəş' },
{ id: 982, wd: 'tear', tr: 'göz yaşı' },
{ id: 983, wd: 'eye', tr: 'göz' },
{ id: 984, wd: 'paper', tr: 'kağız' },
{ id: 985, wd: 'rude', tr: 'kobud' }],
[{ id: 986, wd: 'bell', tr: 'zəng' },
{ id: 987, wd: 'percent', tr: 'faiz' },
{ id: 988, wd: 'candle', tr: 'şam' },
{ id: 989, wd: 'homework', tr: 'ev tapşırığı' },
{ id: 990, wd: 'cat', tr: 'pişik' }]],
[[{ id: 991, wd: 'homework', tr: 'ev tapşırığı' },
{ id: 992, wd: 'paper', tr: 'kağız' },
{ id: 993, wd: 'birthday', tr: 'ad günü' },
{ id: 994, wd: 'boat', tr: 'qayıq' },
{ id: 995, wd: 'account', tr: 'hesab' }],
[{ id: 996, wd: 'river', tr: 'çay' },
{ id: 997, wd: 'beginning', tr: 'başlanğıc' },
{ id: 998, wd: 'favor', tr: 'kömək, yaxşılıq' },
{ id: 999, wd: 'sixteen', tr: 'on altı' },
{ id: 1000, wd: 'famous', tr: 'məşhur' }]],
[[{ id: 1001, wd: 'unusual', tr: 'qeyri-adi' },
{ id: 1002, wd: 'lecture', tr: 'mühazirə, leksiya' },
{ id: 1003, wd: 'garden', tr: 'bağ' },
{ id: 1004, wd: 'smoking', tr: 'siqaret çəkmək' },
{ id: 1005, wd: 'upset', tr: 'məyus' }],
[{ id: 1006, wd: 'intend', tr: 'niyyətində olmaq' },
{ id: 1007, wd: 'fit', tr: 'uyğun gəlmək' },
{ id: 1008, wd: 'half', tr: 'yarı, yarım' },
{ id: 1009, wd: 'perfectly', tr: 'mükəmməl' },
{ id: 1010, wd: 'profitable', tr: 'gəlirli' }]],
[[{ id: 1011, wd: 'slowly', tr: 'yavaş-yavaş' },
{ id: 1012, wd: 'computer', tr: 'kompüter' },
{ id: 1013, wd: 'eight', tr: 'səkkiz' },
{ id: 1014, wd: 'let', tr: 'icazə vermək' },
{ id: 1015, wd: 'classmate', tr: 'sinif yoldaşı' }],
[{ id: 1016, wd: 'bitterly', tr: 'acı-acı, kəskin' },
{ id: 1017, wd: 'disappoint', tr: 'məyus etmək' },
{ id: 1018, wd: 'company', tr: 'şirkət' },
{ id: 1019, wd: 'letter', tr: 'məktub' },
{ id: 1020, wd: 'furniture', tr: 'mebel' }]],
[[{ id: 1021, wd: 'tournament', tr: 'turnir, yarış' },
{ id: 1022, wd: 'apple', tr: 'alma' },
{ id: 1023, wd: 'spacious', tr: 'geniş' },
{ id: 1024, wd: 'clinic', tr: 'klinika' },
{ id: 1025, wd: 'town', tr: 'şəhər' }],
[{ id: 1026, wd: 'at last', tr: 'nəhayət' },
{ id: 1027, wd: 'subject', tr: 'mövzu' },
{ id: 1028, wd: 'funny', tr: 'məzəli, gülməli' },
{ id: 1029, wd: 'beer', tr: 'pivə' },
{ id: 1030, wd: 'prepare', tr: 'hazırla(ş)maq' }]],
[[{ id: 1031, wd: 'favor', tr: 'lütf' },
{ id: 1032, wd: 'compare', tr: 'müqayisə etmək' },
{ id: 1033, wd: 'wallet', tr: 'pul kisəsi' },
{ id: 1034, wd: 'differently', tr: 'fərqli' },
{ id: 1035, wd: 'actress', tr: 'aktrisa' }],
[{ id: 1036, wd: 'sad', tr: 'qəmli' },
{ id: 1037, wd: 'smoking', tr: 'siqaret çəkmək' },
{ id: 1038, wd: 'disappointed', tr: 'məyus etmək' },
{ id: 1039, wd: 'flat', tr: 'mənzil' },
{ id: 1040, wd: 'desk', tr: 'yazı masası' }]],
[[{ id: 1041, wd: 'service', tr: 'xidmət' },
{ id: 1042, wd: 'second', tr: 'ikinci' },
{ id: 1043, wd: 'supplier', tr: 'təchizatçı' },
{ id: 1044, wd: 'milk', tr: 'süd' },
{ id: 1045, wd: 'colleague', tr: 'iş yoldaşı' }],
[{ id: 1046, wd: 'water', tr: 'su' },
{ id: 1047, wd: 'capital', tr: 'paytaxt' },
{ id: 1048, wd: 'newspaper', tr: 'qəzet' },
{ id: 1049, wd: 'meat', tr: 'ət' },
{ id: 1050, wd: 'part', tr: 'hissə' }]],
[[{ id: 1051, wd: 'disturb', tr: 'narahat etmək' },
{ id: 1052, wd: 'agree', tr: 'razılaşmaq' },
{ id: 1053, wd: 'clearly', tr: 'aydın' },
{ id: 1054, wd: 'married', tr: 'evli, ərli' },
{ id: 1055, wd: 'split', tr: 'bölmək' }],
[{ id: 1056, wd: 'such', tr: 'belə' },
{ id: 1057, wd: 'intention', tr: 'niyyət' },
{ id: 1058, wd: 'support', tr: 'dəstəkləmək' },
{ id: 1059, wd: 'decision', tr: 'qərar' },
{ id: 1060, wd: 'apologize', tr: 'üzr istəmək' }]],
[[{ id: 1061, wd: 'pack', tr: 'qablaşdırmaq, yığmaq' },
{ id: 1062, wd: 'clothes', tr: 'paltar' },
{ id: 1063, wd: 'guarantee', tr: 'zəmanət' },
{ id: 1064, wd: 'wrongly', tr: 'səhv' },
{ id: 1065, wd: 'such', tr: 'belə' }],
[{ id: 1066, wd: 'worry', tr: 'narahat olmaq' },
{ id: 1067, wd: 'advise', tr: 'məsləhət vermək' },
{ id: 1068, wd: 'rightly', tr: 'düzgün' },
{ id: 1069, wd: 'satisfactory', tr: 'qaneedici' },
{ id: 1070, wd: 'incorrectly', tr: 'yanlış, səhv' }]],
[[{ id: 1071, wd: 'analyze', tr: 'təhlil etmək' },
{ id: 1072, wd: 'behavior', tr: 'davranış' },
{ id: 1073, wd: 'confirm', tr: 'təsdiqləmək' },
{ id: 1074, wd: 'channel', tr: 'kanal' },
{ id: 1075, wd: 'choose', tr: 'seçmək' }],
[{ id: 1076, wd: 'watch', tr: 'baxmaq' },
{ id: 1077, wd: 'often', tr: 'tez-tez' },
{ id: 1078, wd: 'gym', tr: 'idman zalı' },
{ id: 1079, wd: 'regularly', tr: 'müntəzəm' },
{ id: 1080, wd: 'exercise', tr: 'tapşırıq' }]],
[[{ id: 1081, wd: 'shy', tr: 'utancaq' },
{ id: 1082, wd: 'absolutely', tr: 'tamamilə' },
{ id: 1083, wd: 'certain', tr: 'əmin olmaq' },
{ id: 1084, wd: 'glad', tr: 'şad' },
{ id: 1085, wd: 'optimistic', tr: 'nikbin' }],
[{ id: 1086, wd: 'disappointed', tr: 'məyus' },
{ id: 1087, wd: 'pessimistic', tr: 'pessimist, bədbin' },
{ id: 1088, wd: 'against', tr: 'əleyhinə' },
{ id: 1089, wd: 'talented', tr: 'istedadlı' },
{ id: 1090, wd: 'experienced', tr: 'təcrübəli' }]],
[[{ id: 1091, wd: 'outside', tr: 'bayırdan' },
{ id: 1092, wd: 'city', tr: 'şəhər' },
{ id: 1093, wd: 'hard-working', tr: 'zəhmətkeş' },
{ id: 1094, wd: 'spacious', tr: 'geniş' },
{ id: 1095, wd: 'amazing', tr: 'heyrətamiz' }],
[{ id: 1096, wd: 'useful', tr: 'faydalı' },
{ id: 1097, wd: 'professional', tr: 'peşəkar' },
{ id: 1098, wd: 'lecture', tr: 'mühazirə, leksiya' },
{ id: 1099, wd: 'unusual', tr: 'qeyri-adi, qəribə' },
{ id: 1100, wd: 'low', tr: 'aşağı' }]],
[[{ id: 1101, wd: 'vacation', tr: 'tətil, məzuniyyət' },
{ id: 1102, wd: 'thin', tr: 'nazik' },
{ id: 1103, wd: 'thick', tr: 'qalın' },
{ id: 1104, wd: 'certain', tr: 'əmin olmaq' },
{ id: 1105, wd: 'available', tr: 'bekar olmaq' }],
[{ id: 1106, wd: 'price', tr: 'qiymət' },
{ id: 1107, wd: 'careful', tr: 'diqqətli, qayğıkeş' },
{ id: 1108, wd: 'terrible', tr: 'dəhşətli' },
{ id: 1109, wd: 'confident', tr: 'əmin, arxayın' },
{ id: 1110, wd: 'lucky', tr: 'uğurlu' }]],
[[{ id: 1111, wd: 'cold', tr: 'soyuq' },
{ id: 1112, wd: 'realistic', tr: 'realist' },
{ id: 1113, wd: 'cloudy', tr: 'buludlu' },
{ id: 1114, wd: 'strong', tr: 'güclü' },
{ id: 1115, wd: 'unsuccessful', tr: 'uğursuz' }],
[{ id: 1116, wd: 'lonely', tr: 'tənha' },
{ id: 1117, wd: 'rainy', tr: 'yağışlı' },
{ id: 1118, wd: 'small', tr: 'balaca' },
{ id: 1119, wd: 'windy', tr: 'küləkli' },
{ id: 1120, wd: 'serious', tr: 'ciddi' }]],
[[{ id: 1121, wd: 'rich', tr: 'zəngin, varlı' },
{ id: 1122, wd: 'friendly', tr: 'mehriban' },
{ id: 1123, wd: 'track', tr: 'yol, cığır' },
{ id: 1124, wd: 'favorite', tr: 'sevimli' },
{ id: 1125, wd: 'hospitable', tr: 'qonaqpərvər' }],
[{ id: 1126, wd: 'ill', tr: 'xəstə' },
{ id: 1127, wd: 'confident', tr: 'əmin, arxayın' },
{ id: 1128, wd: 'trip', tr: 'səyahət' },
{ id: 1129, wd: 'were', tr: 'idi' },
{ id: 1130, wd: 'pregnant', tr: 'hamilə' }]],
[[{ id: 1131, wd: 'lucky', tr: 'uğurlu' },
{ id: 1132, wd: 'loyal', tr: 'sadiq' },
{ id: 1133, wd: 'expensive', tr: 'bahalı' },
{ id: 1134, wd: 'box', tr: 'qutu' },
{ id: 1135, wd: 'wrong', tr: 'səhv' }],
[{ id: 1136, wd: 'ago', tr: 'əvvəl' },
{ id: 1137, wd: 'really', tr: 'həqiqətən' },
{ id: 1138, wd: 'interesting', tr: 'maraqlı' },
{ id: 1139, wd: 'last', tr: 'sonuncu, son' },
{ id: 1140, wd: 'far', tr: 'uzaq' }]],
[[{ id: 1141, wd: 'outside', tr: 'bayırdan' },
{ id: 1142, wd: 'reaction', tr: 'reaksiya' },
{ id: 1143, wd: 'inside', tr: 'daxildə, içəridə' },
{ id: 1144, wd: 'careful', tr: 'diqqətli, qayğıkeş' },
{ id: 1145, wd: 'alternative', tr: 'alternativ' }],
[{ id: 1146, wd: 'conference', tr: 'konfrans' },
{ id: 1147, wd: 'partner', tr: 'əməkdaş' },
{ id: 1148, wd: 'wife', tr: 'arvad' },
{ id: 1149, wd: 'month', tr: 'ay' },
{ id: 1150, wd: 'last name', tr: 'soyad' }]],

]};

const wordsForMatch = (state=initialState, action)=>{
  return state
}

export default wordsForMatch