initialState={
  words: [
[[[
{ id: 1, wd: 'I', tr: 'mən' },
{ id: 2, wd: 'think', tr: 'düşünmək' },
{ id: 3, wd: 'we', tr: 'biz' },
{ id: 4, wd: 'understand', tr: 'anlamaq' },
{ id: 5, wd: 'it', tr: 'bu' }],
[{ id: 6, wd: 'speak', tr: 'danışmaq' },
{ id: 7, wd: 'they', tr: 'onlar' },
{ id: 8, wd: 'help', tr: 'kömək' },
{ id: 9, wd: 'me', tr: 'mənə, məni' },
{ id: 10, wd: 'she', tr: 'o (qadın cinsi)' }]],
[[
{ id: 11, wd: 'read', tr: 'oxumaq' },
{ id: 12, wd: 'look', tr: 'baxmaq' },
{ id: 13, wd: 'interesting', tr: 'maraqlı' },
{ id: 14, wd: 'very', tr: 'çox' },
{ id: 15, wd: 'hard', tr: 'sərt' }],
[{ id: 16, wd: 'see', tr: 'görmək' },
{ id: 17, wd: 'this', tr: 'bu' },
{ id: 18, wd: 'mistake', tr: 'səhv' },
{ id: 19, wd: 'also', tr: 'həmçinin' },
{ id: 20, wd: 'house', tr: 'ev' }]],
[[
{ id: 21, wd: 'watch', tr: 'baxmaq' },
{ id: 22, wd: 'go', tr: 'getmək' },
{ id: 23, wd: 'school', tr: 'məktəb' },
{ id: 24, wd: 'every', tr: 'hər, hər bir' },
{ id: 25, wd: 'day', tr: 'gün' }],
[{ id: 26, wd: 'miss', tr: 'darıxmaq' },
{ id: 27, wd: 'sometimes', tr: 'bəzən' },
{ id: 28, wd: 'cinema', tr: 'kino' },
{ id: 29, wd: 'play', tr: 'oynamaq' },
{ id: 30, wd: 'game', tr: 'oyun' }]],
[[
{ id: 31, wd: 'brother', tr: 'qardaş' },
{ id: 32, wd: 'there', tr: 'orada' },
{ id: 33, wd: 'lesson', tr: 'dərs' },
{ id: 34, wd: 'everything', tr: 'hər şey' },
{ id: 35, wd: 'mother', tr: 'ana' }],
[{ id: 36, wd: 'study', tr: 'təhsil almaq' },
{ id: 37, wd: 'always', tr: 'həmişə' },
{ id: 38, wd: 'parent', tr: 'valideyn' },
{ id: 39, wd: 'know', tr: 'bilmək' },
{ id: 40, wd: 'idea', tr: 'ideya, fikir' }]],
[[
{ id: 41, wd: 'more', tr: 'daha çox' },
{ id: 42, wd: 'really', tr: 'həqiqətən, əslində' },
{ id: 43, wd: 'strange', tr: 'qəribə' },
{ id: 44, wd: 'speak', tr: 'danışmaq' },
{ id: 45, wd: 'sister', tr: 'bacı' }],
[{ id: 46, wd: 'live', tr: 'yaşamaq' },
{ id: 47, wd: 'book', tr: 'kitab' },
{ id: 48, wd: 'cat', tr: 'pişik' },
{ id: 49, wd: 'you', tr: 'sən' },
{ id: 50, wd: 'think', tr: 'düşünmek' }]],
[[
  { id: 51, wd: 'and', tr: 'və' },
{ id: 52, wd: 'do', tr: 'etmək' },
{ id: 53, wd: 'buy', tr: 'almaq' },
{ id: 54, wd: 'see', tr: 'görmək' },
{ id: 55, wd: 'abroad', tr: 'xaricdə' }],
[{ id: 56, wd: 'right now', tr: 'indi, bu dəqiqə' },
{ id: 57, wd: 'parent', tr: 'valideyn' },
{ id: 58, wd: 'friend', tr: 'dost' },
{ id: 59, wd: 'again', tr: 'yenə' },
{ id: 60, wd: 'job', tr: 'iş' }],
],
[[{ id: 61, wd: 'she', tr: 'o (qadın cinsi)' },
{ id: 62, wd: 'method', tr: 'metod, üsul' },
{ id: 63, wd: 'go', tr: 'getmək' },
{ id: 64, wd: 'dress', tr: 'paltar' },
{ id: 65, wd: 'doctor', tr: 'həkim' }],
[{ id: 66, wd: 'they', tr: 'onlar' },
{ id: 67, wd: 'like', tr: 'sevmək' },
{ id: 68, wd: 'useful', tr: 'faydalı' },
{ id: 69, wd: 'drink', tr: 'içmək' },
{ id: 70, wd: 'milk', tr: 'süd' }]],
[[{ id: 71, wd: 'want', tr: 'istəmək' },
{ id: 72, wd: 'know', tr: 'bilmək' },
{ id: 73, wd: 'like', tr: 'sevmək' },
{ id: 74, wd: 'agree', tr: 'razılaşmaq' },
{ id: 75, wd: 'with', tr: 'ilə' }],
[{ id: 76, wd: 'discuss', tr: 'müzakirə' },
{ id: 77, wd: 'say', tr: 'demək' },
{ id: 78, wd: 'person', tr: 'şəxs, adam' },
{ id: 79, wd: 'find', tr: 'tapmaq' },
{ id: 80, wd: 'good', tr: 'yaxşı' }]],
[[{ id: 81, wd: 'attract', tr: 'cəlb etmək' },
{ id: 82, wd: 'discuss', tr: 'müzakirə etmək' },
{ id: 83, wd: 'fluently', tr: 'səlist' },
{ id: 84, wd: 'offer', tr: 'təklif' },
{ id: 85, wd: 'interesting', tr: 'maraqlı' }],
[{ id: 86, wd: 'son', tr: 'oğul' },
{ id: 87, wd: 'become', tr: 'olmaq' },
{ id: 88, wd: 'teacher', tr: 'müəllim' },
{ id: 89, wd: 'believe', tr: 'inanmaq' },
{ id: 90, wd: 'make', tr: 'etmək, düzəltmək' }]],
[[{ id: 91, wd: 'need', tr: 'ehtiyac, teləbat' },
{ id: 92, wd: 'without', tr: 'olmadan' },
{ id: 93, wd: 'any', tr: 'hər hansı' },
{ id: 94, wd: 'mistake', tr: 'səhv' },
{ id: 95, wd: 'my ', tr: 'mənim' }],
[{ id: 96, wd: 'call', tr: 'zəng' },
{ id: 97, wd: 'them', tr: 'onlara' },
{ id: 98, wd: 'correct ', tr: 'səhvi düzəltmək' },
{ id: 99, wd: 'correctly', tr: 'düzgün' },
{ id: 100, wd: 'improve', tr: 'təkmilləşdirmək' }]],
[[{ id: 101, wd: 'better', tr: 'daha yaxşı' },
{ id: 102, wd: 'often', tr: 'tez-tez' },
{ id: 103, wd: 'use', tr: 'istifadə' },
{ id: 104, wd: 'internet', tr: 'internet' },
{ id: 105, wd: 'show', tr: 'göstərmək' }],
[{ id: 106, wd: 'result', tr: 'nəticə' },
{ id: 107, wd: 'support', tr: 'dəstək' },
{ id: 108, wd: 'everything', tr: 'hər şey' },
{ id: 109, wd: 'work', tr: 'iş' },
{ id: 110, wd: 'with', tr: 'ilə' }]],
[[{ id: 111, wd: 'seem', tr: 'görünmək, gəlmək' },
{ id: 112, wd: 'boring', tr: 'darıxdırıcı' },
{ id: 113, wd: 'abroad', tr: 'xaricdə' },
{ id: 114, wd: 'hate', tr: 'nifrət' },
{ id: 115, wd: 'ignore', tr: 'məhəl qoymamaq' }],
[{ id: 116, wd: 'happen', tr: 'baş vermək' },
{ id: 117, wd: 'pay', tr: 'ödəmək' },
{ id: 118, wd: 'look for', tr: 'axtarmaq' },
{ id: 119, wd: 'thing', tr: 'şey, əşya' },
{ id: 120, wd: 'word', tr: 'söz' }]],
[[{ id: 121, wd: 'important', tr: 'vacib' },
{ id: 122, wd: 'him', tr: 'onu, ona' },
{ id: 123, wd: 'truth', tr: 'həqiqət' },
{ id: 124, wd: 'those', tr: 'onlar' },
{ id: 125, wd: 'student', tr: 'tələbə' }],
[{ id: 126, wd: 'mother', tr: 'ana' },
{ id: 127, wd: 'show', tr: 'göstərmək' },
{ id: 128, wd: 'brilliant', tr: 'parlaq, əla' },
{ id: 129, wd: 'exam', tr: 'imtahan' },
{ id: 130, wd: 'difficult', tr: 'çətin' }]],
[[{ id: 131, wd: 'word', tr: 'söz' },
{ id: 132, wd: 'her', tr: 'onun (qadın cinsi)' },
{ id: 133, wd: 'like', tr: 'sevmək, istəmək' },
{ id: 134, wd: 'come', tr: 'gəlmək' },
{ id: 135, wd: 'late', tr: 'gec' }],
[{ id: 136, wd: 'home', tr: 'ev' },
{ id: 137, wd: 'work', tr: 'iş' },
{ id: 138, wd: 'solve', tr: 'həll etmək' },
{ id: 139, wd: 'interest', tr: 'maraq' },
{ id: 140, wd: 'happen', tr: 'baş vermək' }]],
[[{ id: 141, wd: 'where', tr: 'harada' },
{ id: 142, wd: 'why', tr: 'nə üçün' },
{ id: 143, wd: 'how', tr: 'necə' },
{ id: 144, wd: 'when', tr: 'nə vaxt' },
{ id: 145, wd: 'free', tr: 'sərbəst, boş' }],
[{ id: 146, wd: 'time', tr: 'vaxt' },
{ id: 147, wd: 'what', tr: 'nə' },
{ id: 148, wd: 'kind', tr: 'nöw' },
{ id: 149, wd: 'much', tr: 'çox' },
{ id: 150, wd: 'get up', tr: 'qalxmaq, ayaqa durmaq' }]],
[[{ id: 151, wd: 'why', tr: 'niyə, nə üçün' },
{ id: 152, wd: 'complain', tr: 'şikayət etmək' },
{ id: 153, wd: 'refuse', tr: 'rədd etmək' },
{ id: 154, wd: 'add', tr: 'əlavə etmək' },
{ id: 155, wd: 'prefer', tr: 'üstünlük vermək' }],
[{ id: 156, wd: 'which', tr: 'hansı' },
{ id: 157, wd: 'channel', tr: 'kanal' },
{ id: 158, wd: 'long', tr: 'uzun' },
{ id: 159, wd: 'take', tr: 'götürmək' },
{ id: 160, wd: 'get', tr: 'çatmaq' }]],
[[{ id: 161, wd: 'where', tr: 'harada' },
{ id: 162, wd: 'disagree', tr: 'razılaşmamaq' },
{ id: 163, wd: 'control', tr: 'nəzarət' },
{ id: 164, wd: 'leave', tr: 'tərk etmək' },
{ id: 165, wd: 'order', tr: 'sifariş' }],
[{ id: 166, wd: 'teacher', tr: 'müəllim' },
{ id: 167, wd: 'give', tr: 'vermək' },
{ id: 168, wd: 'kind', tr: 'nöw' },
{ id: 169, wd: 'example', tr: 'nümunə' },
{ id: 170, wd: 'business', tr: 'biznes' }]],
[[{ id: 171, wd: 'knowledge', tr: 'bilik' },
{ id: 172, wd: 'better', tr: 'daha yaxşı' },
{ id: 173, wd: 'another', tr: 'başqa' },
{ id: 174, wd: 'what', tr: 'nə, hansı' },
{ id: 175, wd: 'right now', tr: 'indicə' }],
[{ id: 176, wd: 'usually', tr: 'adətən' },
{ id: 177, wd: 'get up', tr: 'qalxmaq' },
{ id: 178, wd: 'feel', tr: 'hiss etmək' },
{ id: 179, wd: 'happy', tr: 'xoşbəxt' },
{ id: 180, wd: 'enough', tr: 'kifayət qədər' }]],
[[{ id: 181, wd: 'how', tr: 'necə' },
{ id: 182, wd: 'person', tr: 'şəxs, adam' },
{ id: 183, wd: 'very', tr: 'çox' },
{ id: 184, wd: 'city', tr: 'şəhər' },
{ id: 185, wd: 'long', tr: 'uzun' }],
[{ id: 186, wd: 'daughter', tr: 'qız övladı' },
{ id: 187, wd: 'school', tr: 'məktəb' },
{ id: 188, wd: 'sister', tr: 'bacı' },
{ id: 189, wd: 'live', tr: 'yaşamaq' },
{ id: 190, wd: 'but', tr: 'amma, lakin' }]],
[[{ id: 191, wd: 'try', tr: 'cəhd etmək' },
{ id: 192, wd: 'when', tr: 'nə vaxt' },
{ id: 193, wd: 'free', tr: 'serbəst, pulsuz' },
{ id: 194, wd: 'idea', tr: 'ideya, fikir' },
{ id: 195, wd: 'how', tr: 'necə' }],
[{ id: 196, wd: 'drink', tr: 'içmək' },
{ id: 197, wd: 'coffee', tr: 'qəhvə' },
{ id: 198, wd: 'who', tr: 'kim' },
{ id: 199, wd: 'spend', tr: 'xərcləmək, kəçirmək' },
{ id: 200, wd: 'together', tr: 'birlikdə' }]],
[[{ id: 201, wd: 'book', tr: 'kitab' },
{ id: 202, wd: 'have', tr: 'sahib olmaq' },
{ id: 203, wd: 'home', tr: 'ev' },
{ id: 204, wd: 'music', tr: 'musiqi' },
{ id: 205, wd: 'many', tr: 'çox' }],
[{ id: 206, wd: 'really', tr: 'həqiqətən, əslində' },
{ id: 207, wd: 'correct', tr: 'düzgün' },
{ id: 208, wd: 'also', tr: 'həmçinin' },
{ id: 209, wd: 'brother', tr: 'qardaş' },
{ id: 210, wd: 'exercise', tr: 'tapşırıq, məşq' }]],
[[{ id: 211, wd: 'worry', tr: 'narahat olmaq' },
{ id: 212, wd: 'need', tr: 'ehtiyac' },
{ id: 213, wd: 'tell', tr: 'demək' },
{ id: 214, wd: 'boss', tr: 'müdir' },
{ id: 215, wd: 'always', tr: 'həmişə' }],
[{ id: 216, wd: 'become', tr: 'olmaq' },
{ id: 217, wd: 'read', tr: 'oxumaq' },
{ id: 218, wd: 'improve', tr: 'təkmilləşdirmək' },
{ id: 219, wd: 'grammar', tr: 'qrammatika' },
{ id: 220, wd: 'visit', tr: 'ziyarət etmək' }]],
[[{ id: 221, wd: 'home', tr: 'ev' },
{ id: 222, wd: 'rich', tr: 'zəngin, varlı' },
{ id: 223, wd: 'good', tr: 'yaxşı' },
{ id: 224, wd: 'person', tr: 'şəxs, adam' },
{ id: 225, wd: 'manager', tr: 'menecer' }],
[{ id: 226, wd: 'interesting', tr: 'maraqlı' },
{ id: 227, wd: 'idea', tr: 'ideya, fikir' },
{ id: 228, wd: 'easy', tr: 'asan' },
{ id: 229, wd: 'lazy', tr: 'tənbəl' },
{ id: 230, wd: 'doctor', tr: 'həkim' }]],
[[{ id: 231, wd: 'big', tr: 'böyük' },
{ id: 232, wd: 'simple', tr: 'sadə, asan' },
{ id: 233, wd: 'best', tr: 'ən yaxşı' },
{ id: 234, wd: 'world', tr: 'dünya' },
{ id: 235, wd: 'cheap', tr: 'ucuz' }],
[{ id: 236, wd: 'cold', tr: 'soyuq' },
{ id: 237, wd: 'beautiful', tr: 'gözəl' },
{ id: 238, wd: 'girl', tr: 'qız' },
{ id: 239, wd: 'fine', tr: 'yaxşı, gözəl' },
{ id: 240, wd: 'worse', tr: 'daha pis' }]],
[[{ id: 241, wd: 'such', tr: 'belə, o qədər' },
{ id: 242, wd: 'wise', tr: 'müdrik' },
{ id: 243, wd: 'woman', tr: 'qadın' },
{ id: 244, wd: 'effective', tr: 'effektiv' },
{ id: 245, wd: 'so', tr: 'belə, o qədər' }],
[{ id: 246, wd: 'beautiful', tr: 'gözəl' },
{ id: 247, wd: 'expensive', tr: 'baha' },
{ id: 248, wd: 'clever', tr: 'ağıllı' },
{ id: 249, wd: 'professional', tr: 'peşəkar' },
{ id: 250, wd: 'cheap', tr: 'ucuz' }]],
[[{ id: 251, wd: 'right', tr: 'sağ' },
{ id: 252, wd: 'lesson', tr: 'dərs' },
{ id: 253, wd: 'women', tr: 'qadınlar' },
{ id: 254, wd: 'house', tr: 'ev' },
{ id: 255, wd: 'parent', tr: 'valideyn' }],
[{ id: 256, wd: 'now', tr: 'indi' },
{ id: 257, wd: 'thirty', tr: 'otuz' },
{ id: 258, wd: 'rainy', tr: 'yağmurlu' },
{ id: 259, wd: 'question', tr: 'sual' },
{ id: 260, wd: 'twenty', tr: 'iyirmi' }]],
[[{ id: 261, wd: 'tired', tr: 'yorğun' },
{ id: 262, wd: 'full', tr: 'dolu' },
{ id: 263, wd: 'energy', tr: 'enerji' },
{ id: 264, wd: 'bad', tr: 'pis' },
{ id: 265, wd: 'method', tr: 'metod, üsul' }],
[{ id: 266, wd: 'ineffective', tr: 'qeyri-effektiv' },
{ id: 267, wd: 'woman', tr: 'qadın' },
{ id: 268, wd: 'wise', tr: 'müdrik' },
{ id: 269, wd: 'colleague', tr: 'əməkdaş' },
{ id: 270, wd: 'situation', tr: 'vəziyyət' }]],
[[{ id: 271, wd: 'opinion', tr: 'fikir' },
{ id: 272, wd: 'ready', tr: 'hazır' },
{ id: 273, wd: 'director', tr: 'direktor' },
{ id: 274, wd: 'successful', tr: 'uğurlu' },
{ id: 275, wd: 'project', tr: 'layihə' }],
[{ id: 276, wd: 'obvious', tr: 'açıq-aşkar, aydın' },
{ id: 277, wd: 'global', tr: 'qlobal' },
{ id: 278, wd: 'own', tr: 'sahib' },
{ id: 279, wd: 'flat', tr: 'mənzil' },
{ id: 280, wd: 'boy', tr: 'oğlan' }]],
[[{ id: 281, wd: 'knowledge', tr: 'bilik' },
{ id: 282, wd: 'power', tr: 'güc' },
{ id: 283, wd: 'online', tr: 'onlayn' },
{ id: 284, wd: 'airport', tr: 'hava limanı' },
{ id: 285, wd: 'near', tr: 'yaxın' }],
[{ id: 286, wd: 'level', tr: 'səviyyə' },
{ id: 287, wd: 'article', tr: 'məqalə' },
{ id: 288, wd: 'informative', tr: 'informativ' },
{ id: 289, wd: 'singer', tr: 'müğənni' },
{ id: 290, wd: 'popular', tr: 'populyar' }]],
[[{ id: 291, wd: 'box', tr: 'qutu' },
{ id: 292, wd: 'bag', tr: 'çanta' },
{ id: 293, wd: 'why', tr: 'nə üçün' },
{ id: 294, wd: 'angry', tr: 'qəzəbli, hirsli' },
{ id: 295, wd: 'when', tr: 'nə vaxt' }],
[{ id: 296, wd: 'who', tr: 'kim' },
{ id: 297, wd: 'work', tr: 'iş' },
{ id: 298, wd: 'against', tr: 'əleyhinə' },
{ id: 299, wd: 'far', tr: 'uzaq' },
{ id: 300, wd: 'old', tr: 'köhnə, goca' }]],
[[{ id: 301, wd: 'job', tr: 'iş' },
{ id: 302, wd: 'wrong', tr: 'səhv' },
{ id: 303, wd: 'old', tr: 'köhnə, goca' },
{ id: 304, wd: 'boy', tr: 'oğlan' },
{ id: 305, wd: 'those', tr: 'onlar' }],
[{ id: 306, wd: 'effective', tr: 'effektiv' },
{ id: 307, wd: 'children', tr: 'uşaqlar' },
{ id: 308, wd: 'difficult', tr: 'çətin' },
{ id: 309, wd: 'test', tr: 'sınaq' },
{ id: 310, wd: 'father', tr: 'ata' }]],
[[{ id: 311, wd: 'sunny', tr: 'günəşli' },
{ id: 312, wd: 'from', tr: 'from' },
{ id: 313, wd: 'satisfied', tr: 'qane etmək' },
{ id: 314, wd: 'answer', tr: 'cavab' },
{ id: 315, wd: 'memory', tr: 'yaddaş' }],
[{ id: 316, wd: 'bad', tr: 'pis' },
{ id: 317, wd: 'jeans', tr: 'cins' },
{ id: 318, wd: 'exercise', tr: 'məşq' },
{ id: 319, wd: 'lazy', tr: 'tənbəl' },
{ id: 320, wd: 'dangerous', tr: 'təhlükəli' }]],
[[{ id: 321, wd: 'worse', tr: 'daha pis' },
{ id: 322, wd: 'bathroom', tr: 'hamam' },
{ id: 323, wd: 'kitchen', tr: 'mətbəx' },
{ id: 324, wd: 'boring', tr: 'darıxdırıcı' },
{ id: 325, wd: 'satisfied', tr: 'qane etmək' }],
[{ id: 326, wd: 'box', tr: 'qutu' },
{ id: 327, wd: 'afraid', tr: 'qorxmaq' },
{ id: 328, wd: 'last', tr: 'sonuncu, son' },
{ id: 329, wd: 'enough', tr: 'kifayət qədər' },
{ id: 330, wd: 'news', tr: 'xəbər(-lər)' }]],
[[{ id: 331, wd: 'me', tr: 'mənə, məni' },
{ id: 332, wd: 'right', tr: 'sağ tərəf' },
{ id: 333, wd: 'tired', tr: 'yorğun' },
{ id: 334, wd: 'high', tr: 'yüksək' },
{ id: 335, wd: 'level', tr: 'səviyyə' }],
[{ id: 336, wd: 'manner', tr: 'ədəb' },
{ id: 337, wd: 'against', tr: 'əleyhinə' },
{ id: 338, wd: 'glad', tr: 'şad' },
{ id: 339, wd: 'door', tr: 'qapı' },
{ id: 340, wd: 'open', tr: 'açıq, açmaq' }]],
[[{ id: 341, wd: 'laugh', tr: 'gülmək' },
{ id: 342, wd: 'waste', tr: 'israf etmək' },
{ id: 343, wd: 'summer', tr: 'yay' },
{ id: 344, wd: 'winter', tr: 'qış' },
{ id: 345, wd: 'adapt', tr: 'uyğunlaşma' }],
[{ id: 346, wd: 'condition', tr: 'vəziyyət, şərt' },
{ id: 347, wd: 'soon', tr: 'tezliklə' },
{ id: 348, wd: 'possible', tr: 'mümkün' },
{ id: 349, wd: 'prepare', tr: 'hazırlaşmaq' },
{ id: 350, wd: 'exam', tr: 'imtahan' }]],
[[{ id: 351, wd: 'atmosphere', tr: 'ab-hava' },
{ id: 352, wd: 'surprising', tr: 'təəccüblü' },
{ id: 353, wd: 'frighten', tr: 'qorxutmaq' },
{ id: 354, wd: 'nowadays', tr: 'hazırki vaxtda' },
{ id: 355, wd: 'perfectly', tr: 'mükəmməl, çox gözəl' }],
[{ id: 356, wd: 'realize', tr: 'dərk etmək' },
{ id: 357, wd: 'desk', tr: 'yaza masası' },
{ id: 358, wd: 'longest', tr: 'ən uzun' },
{ id: 359, wd: 'river', tr: 'çay' },
{ id: 360, wd: 'write', tr: 'yazmaq'}]],
[[{ id: 361, wd: 'compete', tr: 'rəqabət' },
{ id: 362, wd: 'enjoy', tr: 'zövq almaq' },
{ id: 363, wd: 'behave', tr: 'davranmaq' },
{ id: 364, wd: 'strangely', tr: 'qəribə' },
{ id: 365, wd: 'elder', tr: 'daha yaşlı' }],
[{ id: 366, wd: 'younger', tr: 'cavan' },
{ id: 367, wd: 'meaning', tr: 'məna' },
{ id: 368, wd: 'expression', tr: 'İfadə' },
{ id: 369, wd: 'alone', tr: 'tək, tənha' },
{ id: 370, wd: 'experience', tr: 'təcrübə' }]],
[[{ id: 371, wd: 'meaning', tr: 'məna' },
{ id: 372, wd: 'sport', tr: 'idman' },
{ id: 373, wd: 'great', tr: 'böyük' },
{ id: 374, wd: 'sure', tr: 'əmin, arxayın' },
{ id: 375, wd: 'summer', tr: 'yay' }],
[{ id: 376, wd: 'movie', tr: 'film' },
{ id: 377, wd: 'traveling', tr: 'səyahət etmək' },
{ id: 378, wd: 'wonderful', tr: 'möhtəşəm, çox gözəl' },
{ id: 379, wd: 'feeling', tr: 'hiss etmək' },
{ id: 380, wd: "o'clock", tr: 'saat' }]],
[[{ id: 381, wd: 'celebrate', tr: 'qeyd etmək' },
{ id: 382, wd: 'birthday', tr: 'ad günü' },
{ id: 383, wd: 'progress', tr: 'tərəqqi' },
{ id: 384, wd: 'enjoy', tr: 'zövq almaq' },
{ id: 385, wd: 'simplicity', tr: 'sadəlik' }],
[{ id: 386, wd: 'hope', tr: 'ümid' },
{ id: 387, wd: 'sad', tr: 'qəmli' },
{ id: 388, wd: 'salary', tr: 'maaş, məvacib' },
{ id: 389, wd: 'low', tr: 'aşagı' },
{ id: 390, wd: 'necessary', tr: 'gərəkli, vacib' }]],

],
[],
[],
[],
[]
  ],
};

const wordsForMatch = (state=initialState, action)=>{
  return state
}

export default wordsForMatch